### ISSUE TITLE
Add PUT and GET support

### ISSUE THREAD

**Issue by smtakeda** [snowflakedb/pdo_snowflake#102]
Not v1.0 but future version.

**Comment by smtakeda** [comment]
We may implement this earlier as I hear more demands.

**Comment by notkriswagner** [comment]
https://github.com/bji/libs3 might be an interesting choice.

**Comment by smtakeda** [comment]
@notkriswagner, this task is being important as ODBC needs the same functionality too. When you design the API, can you make the file transfer API in public (but more or less internal use only) so that ODBC can make calls?
An ultimate goal is rewrite ODBC based on C/C++ API, but it won't happen next couple of months.

**Comment by smtakeda** [comment]
No plan to support PUT and GET for PDO at the moment.
