### ISSUE TITLE
Review logging

### ISSUE THREAD

**Issue by smtakeda** [snowflakedb/pdo_snowflake#103]
Goals
- Ensure the log includes required info for debug.
- Ensure the log can be enabled and disabled as the customer needs.
- Ensure the log location can be specified.
- Ensure the log doesn't include sensitive information, i.e., password, private key

**Comment by smtakeda** [comment]
This is one of the last step before GA.

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
