### ISSUE TITLE
Map data types between Snowflake and PHP

### ISSUE THREAD

**Issue by smtakeda** [snowflakedb/pdo_snowflake#11]
Goal
- Clarify data type mapping between Snowflake and PHP
-- Converting from Snowflake to PHP
-- Converting from PHP to Snowflake

**Comment by smtakeda** [comment]
One concern is PHP doesn't have a native decimal types. It is either integer or float.
http://php.net/manual/en/language.types.intro.php

BC Math extension seems to fill the gap.
http://de2.php.net/manual/en/ref.bc.php

**Comment by smtakeda** [comment]
Will look into this closely. 
In particular, cross data type mapping should be clarified, e.g., INT vs STRING.

**Comment by sfc-gh-dszmolka** [comment]
marking this old issue as closed for now. If it's still something we would need to address, please commend and we can reopen.
