### ISSUE TITLE
Need C Unittest framework

### ISSUE THREAD

**Issue by smtakeda** [snowflakedb/pdo_snowflake#116]
As we have more test cases as examples, we need better test framework and runners to run tests automatically, detect and aggregate errors.

I'm thinking of adding either one of them:
https://libcheck.github.io/check/doc/check_html/
https://cmocka.org/

**Comment by notkriswagner** [comment]
https://github.com/bji/libs3 might be an interesting choice.

**Comment by smtakeda** [comment]
The above library is for PUT and GET support? https://github.com/snowflakedb/pdo_snowflake/issues/102 is the one.

**Comment by notkriswagner** [comment]
Ah yea, my mistake.

**Comment by notkriswagner** [comment]
Unity and CMock (http://www.throwtheswitch.org/unity/ http://www.throwtheswitch.org/cmock) is also an interesting choice looks similar to cmocka. Although, I'm not a fan of the Ruby build system. Also looks like its aimed mostly at embedded systems.

**Comment by notkriswagner** [comment]
From looking at all the choices, it seems like cmocka is the best, since Unity and CMock seem to require at least minimum Ruby usage.
