### ISSUE TITLE
Memory consumption

### ISSUE THREAD

**Issue by 0bp** [snowflakedb/pdo_snowflake#148]
Due to reasons how we use snowflake we have to use VARCHAR(16777216). Running a very simple query on a table that has 31 of those varchar columns yields a PHP memory consumption of 520 MB for only fetching one row.

It seems the driver allocates memory in PHP based on column definitions.

```php
$db = new PDO("snowflake:XXX","XXX","1XXX");
$db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
$db->exec('use warehouse "XXX"');
$db->exec('use database "XXX"');
$db->exec('use schema "XXX"');
$result = $db->query('select * from "XXX" LIMIT 1');
var_dump(memory_get_usage());
```

**Comment by smtakeda** [comment]
yeah, that's what I noticed and didn't have a chance to improve it. Will work on it after other blocking issue is addressed.

**Comment by smtakeda** [comment]
Merged the fix. The new PDO version is 0.1.2. Can you please try?

**Comment by smtakeda** [comment]
Added `var_dump(memory_get_usage());` to the test case:
https://github.com/snowflakedb/pdo_snowflake/blob/master/tests/twentystring.phpt

Before this fix:
int(335934552)

After this fix:
int(389912)

**Comment by 0bp** [comment]
With a fresh build from today I get
```
php: symbol lookup error: /usr/lib/php/20170718/pdo_snowflake.so: undefined symbol: OpenSSL_version_num
```

**Comment by 0bp** [comment]
Negative. It's still the same amount of memory in use.

Output of `php -i`:
```
pdo_snowflake

PDO Driver for Snowflake => enabled
Version => 0.1.2
```

**Comment by smtakeda** [comment]
That sounds like strange. The cause could be either the metric we are checking are different or the build was not correct. Let me see how I can give you the SO file. What is PHP version?

**Comment by 0bp** [comment]
PHP 7.2.5

**Comment by 0bp** [comment]
That looks fine. I'll check the manual build again.

**Comment by smtakeda** [comment]
Closing this issue for now.

In the production release, we are going to distribute the binaries.
