### ISSUE TITLE
Segmentation fault when using named placeholders

### ISSUE THREAD

**Issue by plsoucy-tapclicks** [snowflakedb/pdo_snowflake#152]
We're trying to use named placeholders as described in the first example at http://php.net/manual/en/pdostatement.bindparam.php (and as we normally do when we have to write raw SQL) and are getting segmentation faults. It turns out that this works:

(SQL is something like DELETE FROM a WHERE a.campaign_id=:campaign_id)

```
$query = $sf_db->prepare(str_replace(':campaign_id', '?', $sql));
$query->bindParam(1, $campaign_id);
$query->execute();
```
... but this causes a segmentation fault:

```
$query = $sf_db->prepare($sql);
$query->bindParam(':campaign_id', $campaign_id);
$query->execute();
```

Details from the core dump:
```
Program terminated with signal 11, Segmentation fault.
#0  pdo_sf_array_list_get (al=0x0, index=0) at /home/programs/snowflake-pdo/snowflake_arraylist.c:57
57          if (al->size <= index) {
```

Can you please look into this and tell us when/if we can expect named placeholders to be properly supported? Thanks.

**Comment by notkriswagner** [comment]
At this time we don't support named placeholders, but the driver should not be segfaulting when named placeholders are used. Instead the driver should just return an error until named placeholders are supported.

**Comment by notkriswagner** [comment]
Incorrectly closed this issue instead of #153 . Reopening

**Comment by notkriswagner** [comment]
@plsoucy-tapclicks Can you verify that there is no longer a segmentation fault and that you now get a exception instead?

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
