### ISSUE TITLE
Got this working earlier today, now I just get nginx 502 gateway timeouts

### ISSUE THREAD

**Issue by tvpmb** [snowflakedb/pdo_snowflake#166]
I was able to connect and pull data from snowflake earlier, now I can't get anything but 502 timeouts, does anyone have any insight here?

2018/11/16 02:02:08 [error] 2595#2595: *15 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: _, request: "GET /datasync/snowflake-test.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "ec2..."

I'm just trying to run the sample connection script. PHP is working and pdo-snowflake is installed, I can see that on my phpinfo() test page. Whenever I run the snowflake test php script, I get a 502. 

Any ideas?

**Comment by tvpmb** [comment]
Looks like there is a problem with the OCSP in US-WEST region, they suggest using "insecure" mode to connect, is there an option in PDO to do this? setAttribute() perhaps? Is there any documentation on options that can be passed?

**Comment by notkriswagner** [comment]
Yes I just added this to the PDO Driver a few days ago. In the DSN string add `insecure_mode=true` and it will skip the OCSP check.

**Comment by notkriswagner** [comment]
The PDO Driver is still being actively developed and is not ready for production systems. As we improve the PDO driver, I'll make sure that we also add more documentation on usage.

**Comment by tvpmb** [comment]
awesome - thanks @notkriswagner now that I can connect again and can stop pulling my hair out trying to find the issue, everything seems to be running well!
