### ISSUE TITLE
Dockerfile configuration to build and install pdo_snowflake

### ISSUE THREAD

**Issue by tvpmb** [snowflakedb/pdo_snowflake#168]
Hi Everyone,

Just wanted to share my dockerfile configuration with the group as I hope this helps someone who wishes to add pdo_snowflake to their installation.

```
FROM php:7.1-fpm

RUN useradd -u 1000 local

RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libpng-dev \
        apt-utils \
        libxml2-dev \
        zlib1g-dev \
        zip \
        libcurl3 \
        libpcre3-dev \
        libcurl4-openssl-dev \
    && docker-php-ext-install -j$(nproc) iconv mcrypt pdo_mysql mbstring \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-install soap

RUN apt-get install -y git

RUN docker-php-ext-configure bcmath \
    && docker-php-ext-install -j$(nproc) bcmath

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ --filename=composer

COPY xdebug-2.5.4.tgz /usr/src/php/ext/xdebug.tgz
RUN tar -xf /usr/src/php/ext/xdebug.tgz -C /usr/src/php/ext/ && \
    rm /usr/src/php/ext/xdebug.tgz && \
    docker-php-ext-install xdebug-2.5.4
COPY xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini

# install the jq library to support the snowflake build
RUN apt-get install -y jq

# clone pdo_snowflake repo
RUN mkdir /tmp/snowflake \
    && git clone https://github.com/snowflakedb/pdo_snowflake.git /tmp/snowflake

# copy over the test credentials
COPY parameters.json /tmp/snowflake/

# run the compile command
# move the compiled lib to the correct location
RUN cd /tmp/snowflake \
    && export PHP_HOME=/usr/bin \
    && ./scripts/build_pdo_snowflake.sh \
    && cp /tmp/snowflake/libsnowflakeclient/cacert.pem /tmp/snowflake/modules/pdo_snowflake.so /usr/local/lib/php/extensions/no-debug-non-zts-20160303/

# add the configuration inis to the right locations
COPY pdo_snowflake.ini /usr/local/etc/php/conf.d/pdo_snowflake.ini
```

**Comment by c00p3r** [comment]
@tvpmb Hey! trying to add this to my local setup
almost there but I don't get what that `parameters.json` is?
could give me a hint? what should be inside? or where in the docs it's being described?
I'd appreciate any help

**Comment by oranges13** [comment]
Mine does not have a `pdo_snowflake.ini`, where did that come from?

**Comment by milesjmccloskey** [comment]
In order to run the test scripts, you must have jq installed.

[Prepare for Test](https://github.com/snowflakedb/pdo_snowflake#id15)
Create a parameter file parameters.json under pdo_snowflake directory:

{
    "testconnection": {
        "SNOWFLAKE_TEST_USER":      "<your_user>",
        "SNOWFLAKE_TEST_PASSWORD":  "<your_password>",
        "SNOWFLAKE_TEST_ACCOUNT":   "<your_account>",
        "SNOWFLAKE_TEST_WAREHOUSE": "<your_warehouse>",
        "SNOWFLAKE_TEST_DATABASE":  "<your_database>",
        "SNOWFLAKE_TEST_SCHEMA":    "<your_schema>",
        "SNOWFLAKE_TEST_ROLE":      "<your_role>"
    }
}
Call env.sh script to set the test connection parameters in the environment variables.

./scripts/env.sh && env | grep SNOWFLAKE_TEST > testenv.ini
