### ISSUE TITLE
Investigate High CPU/Memory Leak During a hung connection

### ISSUE THREAD

**Issue by sfc-gh-kwagner** [snowflakedb/pdo_snowflake#171]
During a recent OCSP outage, the PDO driver was reported as taking over 100% CPU usage trying to connect to Snowflake (the connection was hung waiting for the OCSP check). This issue most likely exists in the cURL layer, but we need to investigate to be sure.

**Comment by sfc-gh-jtang** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link Snowflake Community is the fastest way to get a response.
