### ISSUE TITLE
TIMESTAMP_NTZ values are returned formatted differently than with the PDO driver

### ISSUE THREAD

**Issue by plsoucy-tapclicks** [snowflakedb/pdo_snowflake#173]
We're looking to get TIMESTAMP_NTZ values in the YYYY-MM-DD HH24:MI:SS format.

Regardless of what we set for TIMESTAMP_NTZ_OUTPUT_FORMAT at the session level when using the PDO driver, we get values like 2019-01-02 18:38:11.000000000

The same query, with the ODBC driver, will return something like 2019-01-02 18:38:11 (without the point and 9 zeros at the end).

Is there currently a way to get the TIMESTAMP_NTZ values without the 9 zeros at the end with the PDO driver, like we seem to get by default with the ODBC driver? I understand we could apply formatting in the query or when post-processing the results we get from the Snowflake driver, but we're trying to avoid that if possible.

Thanks!

**Comment by notkriswagner** [comment]
Hi @plsoucy-tapclicks,

As of right now, we don't honor any timestamp output format besides that default format in either the PDO driver or the underlying C library. I've created this issue snowflakedb/libsnowflakeclient#120 to track adding this functionality in our C API. Once that's done I'll update the PDO driver to take advantage of this new functionality.

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
