### ISSUE TITLE
PDOException  could not find driver

### ISSUE THREAD

**Issue by neorganic** [snowflakedb/pdo_snowflake#175]
I have followed the guide for pdo_snowflake instalation, but on this:

```  $dbh = new PDO("snowflake:account=$account", $user, $password);``` line I get the following error:

```PDOException  could not find driver```

Any leads, to debug this?

---
I am on Ubuntu 18.04 LTS, php 7.2

**Comment by tomasfejfar** [comment]
Most probably you're missing `extension=pdo_snowflake.so` in your php.ini. Maybe it's a different ini you added it to? Check output of phpinfo() inside your code - put `phpinfo();die();` above the $dbh... line and see if the driver is installed. You can check which php.ini is loaded. There may be different php.ini for cli and for apache/fpm.

**Comment by notkriswagner** [comment]
Hi,

The first thing you should do is to run your `php` with the `-m` option (with all of your other cmd line options as well) to see that the snowflake driver is loaded? Another common issue is that the pdo_snowflake driver is not specified as an extension in the ini file or on the command line. On my machine I run `~/php72/install-php-7.2.9/bin/php -dextension=modules/pdo_snowflake.so -m` and I get this as my output:

```
[PHP Modules]
Core
ctype
date
dom
fileinfo
filter
hash
iconv
json
libxml
pcre
PDO
pdo_snowflake
pdo_sqlite
Phar
posix
Reflection
session
SimpleXML
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
```

**Comment by notkriswagner** [comment]
@neorganic Another thing to mention is that you must also specify the cacert location in the .ini file like `pdo_snowflake.cacert=/path/to/cacert`. This is another common error when using the Snowflake PDO driver.

**Comment by neorganic** [comment]
Yeah I am missing the `pdo_snowflake` module : 
```
 /usr/bin/php -dextension=modules/pdo_snowflake.so -m | grep snowflake
PHP Warning:  PHP Startup: Unable to load dynamic library 'modules/pdo_snowflake.so' (tried: modules/pdo_snowflake.so (modules/pdo_snowflake.so: cannot open shared object file: No such file or directory), /usr/lib/php/20170718/modules/pdo_snowflake.so.so (/usr/lib/php/20170718/modules/pdo_snowflake.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```
To be clear - I must use the cacert.pem from this repo ? the instructions on this part is not so clear.

**Comment by neorganic** [comment]
Btw this doesn't seem correct, right?

![image](https://user-images.githubusercontent.com/19753711/53088298-fc974900-3511-11e9-9a4f-1f829d92b753.png)

**Comment by notkriswagner** [comment]
@neorganic You can use any cacert, either the one we provide or the one on your system. 

The line for extension that you added to the php.ini file should be:
```extension=modules/pdo_snowflake.so```

not 
```extension=pdo_snowflake.so```

Are you in the `conf.d` dir there? If so, then that is right. All of those files with links link to `.ini` files that come standard as part of the php installation, where as the `.ini` file for snowflake is generated and placed there on installation.

Would you mind sharing the contents of your `20-pdo_snowflake.ini` file?

**Comment by neorganic** [comment]
> Libraries have been installed in:
   /home/mantas/Desktop/temp/pdo_snowflake/modules
I think this should be the core issue, right?
I am setting `PHP_HOME` with: `export PHP_HOME=/usr`


> Would you mind sharing the contents of your `20-pdo_snowflake.ini` file?
```
extension=pdo_snowflake.so
pdo_snowflake.cacert=/etc/php/7.2/fpm/conf.d/cacert.pem
# pdo_snowflake.logdir=/tmp     # location of log directory
# pdo_snowflake.loglevel=DEBUG  # log level
```

**Comment by notkriswagner** [comment]
@neorganic 

With respect to the "Are you in the `conf.d` dir there?" I was referring to the comment where you posted a picture of a directory's contents and said "Btw this doesn't seem correct, right?". I was wondering which directory that is the contents of.

> All my modules are in `/usr/lib/php/20170718/` and I would expect that `snowflake_pdo.so` should also appear there?

You may have to move the pdo_snowflake.so to the directory that you mentioned above. I generally use a different flavor of Linux for dev and testing. Let me see if I can reproduce this if I use Ubuntu

**Comment by neorganic** [comment]
@notkriswagner  moved `snowflake_pdo.so` to `/usr/lib/php/20170718/` path and also  removed all the `modules` references -  restarted nginx/php-fpm and finally pdo_snowflake seems to be installed!  

![image](https://user-images.githubusercontent.com/19753711/53346617-0c52cb00-3920-11e9-8442-8b892dcd7037.png)
Getting a new issue now, but I think it's safe to call a entirely a different kind of issue:
```SQLSTATE[57P03]: Cannot connect now: 606 No active warehouse selected in the current session. Select an active warehouse with the 'use warehouse' command.```

**Comment by notkriswagner** [comment]
@neorganic Glad you got it working. Can I close this ticket?

**Comment by neorganic** [comment]
@notkriswagner  yeah!
