### ISSUE TITLE
SQLSTATE[57P03]: Cannot connect now: 606 No active warehouse selected in the current session. Select an active warehouse with the 'use warehouse' command.

### ISSUE THREAD

**Issue by neorganic** [snowflakedb/pdo_snowflake#179]
```SQLSTATE[57P03]: Cannot connect now: 606 No active warehouse selected in the current session. Select an active warehouse with the 'use warehouse' command.```

Getting this on line : 
``` 
$sth = $dbh->query("select ID, NAME  from DB_V2.INSIGHTS.ACCOUNT
                order by ID;");
```
Any leads how can I set my warehouse?

**Comment by neorganic** [comment]
Just solved this, so adding extra query before the first query solves my issue - e.g. : 
```
    $dbh->query("USE WAREHOUSE MY_WH;");
```

**Comment by notkriswagner** [comment]
@neorganic Yes you have to use a warehouse in your session to be able to run queries.

**Comment by allenp** [comment]
Alternatively:

Add 'warehouse=MY_WH' in the dsn string when you create your PDO object to avoid doing "USE WAREHOUSE"
