### ISSUE TITLE
activating pdo_snowflake on linux breaks mssqlsrv

### ISSUE THREAD

**Issue by swiffer** [snowflakedb/pdo_snowflake#182]
as soon as pdo_snowflake is enabled mssqlsrv breaks - see Microsoft/msphpsql#939

 ## PHP Driver version or file name
v5.6.0
 ## SQL Server version
11.0.7469.6
 ## Client operating system
 18.04.1-Ubuntu
 ## PHP version
 PHP 7.3.2-3+ubuntu18.04.1+deb.sury.org+1 (cli) 
 ## Microsoft ODBC Driver version
 17.3.1.1-1
 ## Problem description
 ```
Error: [PDOException] SQLSTATE[08001]: [unixODBC][Microsoft][ODBC Driver 17 for SQL Server]SSL Provider: [error:140A90A1:SSL routines:SSL_CTX_new:library has no ciphers] in
```
## Expected behavior and actual behavior
Query should execute normally

**Comment by swiffer** [comment]
(it works on windows (PHP7.2.15 / 64bit / TS))

**Comment by notkriswagner** [comment]
Hi @swiffer ,

Currently, the PDO driver is untested on PHP 7.3 (but tested on 7.0-7.2). I have a few questions about this:

- How did you build the PDO driver for 7.3.2? Using the build instructions provided? Can you provide a full list of build instructions here.
- Using NTS or TS?
- Have you tried building this with PHP 7.2 on Linux and see if the same issue occurs?
- When you say it works on Windows do you mean that you loaded the `pdo_snowflake` driver as well as the `mssqlsrv` driver and this didn't occur?

**Comment by swiffer** [comment]
- Built using the instructions from the README.md https://github.com/snowflakedb/pdo_snowflake#build-pdo-driver-on-linux
- I'm using the PHP packages provided by Ondřej Surý for Ubuntu 18.04 https://launchpad.net/~ondrej/+archive/ubuntu/php
- Tried with PHP 7.2 and PHP 7.3
- Yes, correct - when using PHP 7.2.15 TS 64bit on Windows loading both - pdo_sqlsrv + pdo_snowflake works fine

**Comment by notkriswagner** [comment]
@swiffer Have you tried using PHP 7.2 on Linux?

**Comment by swiffer** [comment]
Yes, Same behaviour

**Comment by notkriswagner** [comment]
@swiffer Same behavior as on Windows with 7.2 or same behavior as Linux with 7.3? I'm trying to see if this is an issue with Linux or PHP 7.3.

**Comment by swiffer** [comment]
Sorry for Not beeing clear enough - faulty behaviour on PHP 7.2 and 7.3 in Ubuntu 18.04

**Comment by swiffer** [comment]
What Version of openssl are You bundling ? Can't you use phps built in openssl libraries instead?

**Comment by notkriswagner** [comment]
Okay, I'll put this on the queue and check it out when possible. We bundle our own version of OpenSSL because there is no anchored version that comes with PHP and so people can have a multitude of different OpenSSL versions installed and working with PHP. Some of these versions can be quite old and have noted vulnerabilities and we don't want to link with code that has known CVEs when we could just have a more up-to date version as part of `libsnowflakeclient`.

**Comment by swiffer** [comment]
@notkriswagner Thanks! Have you been able to reproduce the problem. Understand the philosophy of not linking against code with known CVEs. The problem is that 1.0.2r and 1.1.0j seem to use different methods for getting available ciphers.

**Comment by notkriswagner** [comment]
I was able to reproduce this issue. Seems like other users also have this issue on SUSE 15 which uses OpenSSL 1.1.0+ (see https://github.com/Microsoft/msphpsql/issues/680). At this time we are not going to downgrade the version of OpenSSL that we use for `pdo_snowflake` or `libsnowflakeclient`. At some point, Microsoft may end up building a mssqlsrv that works with SUSE 15 out of the box, which would solve your issue.
