### ISSUE TITLE
[Question] How to store array or json to snowflake?

### ISSUE THREAD

**Issue by mkantautas** [snowflakedb/pdo_snowflake#183]
When using snowflake with php I encountered an issue, that it's very tricky to insert e.g. array datatypes to snowflake. Possibly you know a good approach?

**Comment by notkriswagner** [comment]
Here is an example from one of our tests on how to insert array or json objects to snowflake:

https://github.com/snowflakedb/pdo_snowflake/blob/master/tests/selectvar.phpt

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
