### ISSUE TITLE
PDO issue when connecting from PHP

### ISSUE THREAD

**Issue by makkena6** [snowflakedb/pdo_snowflake#184]
Followed the exact steps in doc but still says PDO error and drivers not found. I even ran the cmd statement and snowflake pdo does not show up. I have placed the dll file under php extras and gave all references below in php.ini file but still the same issue when connecting from PHP(windows)

extension=php_pdo_snowflake.dll
extension=pdo_snowflake.so
extension=modules/pdo_snowflake.so
extension=php_pdo_snowflake.dll
extension=pdo_snowflake.so
extension=modules/pdo_snowflake.so
pdo_snowflake.cacert=C:\xampp\php\cacert.pem

**Comment by notkriswagner** [comment]
The `pdo_snowflake.so` references won't work since you're referring to a linux library while you're on Windows. Try putting the full path to the `php_pdo_snowflake.dll` file in your config.

**Comment by makkena6** [comment]
Thank you, i did try that like below and restarted the apache. Still same issue though
extension=C:\xampp\php\ext\php_pdo_snowflake.dll
pdo_snowflake.cacert=C:\xampp\php\cacert.pem

----in my php
$dbh = new PDO("snowflake:account=ug16052.us-east-2.azure;region=us-east-2.azure", "rmakkena", "R0cket18");
$dbh->setAttribute( PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION );
echo "Connected\n";

**Comment by notkriswagner** [comment]
Okay, can you post the following information:

- Which version of PHP are you using?
- What Platform? (include OS, version, and platform)

Btw, the `region` parameter in your connection string is redundant since you include the region in the `account` field

**Comment by makkena6** [comment]
testing this currently on my windows 10 machine.  PHP Version 7.1.26

**Comment by notkriswagner** [comment]
xampp with PHP 7.1.26?

**Comment by makkena6** [comment]
XAMPP with PHP right. I installed with default options so i assume non-zts

**Comment by notkriswagner** [comment]
Cool, I'm going to put this in the backlog and I'll post a message here when I have an update.

**Comment by makkena6** [comment]
Thanks very much for the update.  This will be a great feature add for windows especially for writeback from BI platform. I can try nodejs in the meantime and check if i can make it work.

**Comment by makkena6** [comment]
Is this available for windows now? and does this work for mac? don't see any instruction for mac os

**Comment by notkriswagner** [comment]
We haven't worked on this specific issue yet, but the driver does build and work on Windows. The instructions for macOS are the same as for Linux. I'll update the documentation to specify that

**Comment by Heisenberg87** [comment]
Hey @sfc-gh-kwagner 

I am similar issue, however I am using php 7.4.13. 

extension=C:\xampp\php\php-7.4.13\ext\php_pdo_snowflake.dll
pdo_snowflake.cacert=C:\xampp\php\php-7.4.13\cacert.pem

**Comment by sfc-gh-kwagner** [comment]
Hi @Heisenberg87 can you reach out to Snowflake support for help with this issue since this driver is GA, they are the proper channel to reach out to

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
