### ISSUE TITLE
v1.0.0 deadline ?

### ISSUE THREAD

**Issue by jcolfej** [snowflakedb/pdo_snowflake#188]
Is there a deadline set for the release of the driver?
This is a blocking point on the use of Snowflake in our company...

**Comment by smtakeda** [comment]
At the moment, we are planning to release v1 by Nov 2019.
Please reach out the customer support for further questions.

**Comment by zoltan-fedor** [comment]
Hi @smtakeda, Is the Nov 2019 timeline still valid for v1?

**Comment by smtakeda** [comment]
Not confirmed. Given priorities, we are still juggling tasks for the following quarters.

**Comment by zoltan-fedor** [comment]
Thanks. Could you please let us know once you have an idea about the expected timeline for v1?
Thanks
