### ISSUE TITLE
OpenSSL error on install for linux

### ISSUE THREAD

**Issue by dlinstedt** [snowflakedb/pdo_snowflake#189]
[unix ~]$ php -v
/opt/cpanel/ea-php71/root/usr/bin/php: symbol lookup error: /opt/alt/php71/usr/lib64/php/modules/pdo_snowflake.so: undefined symbol: OpenSSL_version_num

PHP Version: PHP Version 7.1.30
CONFIG:

  | './configure'   '--disable-dependency-tracking' '--prefix=/usr' '--exec-prefix=/usr'  '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc'  '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib64'  '--libexecdir=/usr/libexec' '--sharedstatedir=/var/lib'  '--mandir=/usr/share/man' '--infodir=/usr/share/info'  '--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu'  '--target=x86_64-redhat-linux-gnu' '--program-prefix='  '--prefix=/opt/alt/php71' '--exec-prefix=/opt/alt/php71'  '--bindir=/opt/alt/php71/usr/bin' '--sbindir=/opt/alt/php71/usr/sbin'  '--sysconfdir=/opt/alt/php71/etc' '--datadir=/opt/alt/php71/usr/share'  '--includedir=/opt/alt/php71/usr/include'  '--libdir=/opt/alt/php71/usr/lib64'  '--libexecdir=/opt/alt/php71/usr/libexec' '--localstatedir=/var'  '--with-curl=/opt/alt/curlssl/usr' '--sharedstatedir=/usr/com'  '--mandir=/opt/alt/php71/usr/share/man'  '--infodir=/opt/alt/php71/usr/share/info' '--cache-file=../config.cache'  '--with-libdir=lib64' '--with-config-file-path=/opt/alt/php71/etc'  '--with-config-file-scan-dir=/opt/alt/php71/link/conf' '--disable-debug'  '--enable-calendar' '--enable-exif' '--enable-ftp'  '--enable-gd-native-ttf' '--enable-huge-code-pages' '--enable-opcache'  '--enable-opcache-file' '--enable-shmop' '--enable-xml' '--with-bz2'  '--with-freetype-dir=/usr' '--with-gettext' '--with-gmp' '--with-iconv'  '--with-jpeg-dir=/usr' '--with-kerberos' '--with-layout=GNU'  '--with-libxml-dir=/opt/alt/libxml2/usr' '--with-mhash'  '--with-openssl-dir=/opt/alt/openssl' '--with-openssl=/opt/alt/openssl'  '--with-pcre-regex=/opt/alt/pcre/usr' '--with-pic' '--with-png-dir=/usr'  '--with-readline' '--with-t1lib=/opt/alt/t1lib/usr'  '--with-webp-dir=/usr' '--with-xpm-dir=/usr' '--with-zlib'  '--with-zlib-dir=/usr' '--without-gdbm' '--without-pear'  '--with-pcre-jit' '--enable-pcntl' '--with-litespeed'  '--with-recode=shared,/usr' '--without-mysqli' '--disable-mbstring'  '--disable-bcmath' '--disable-dba' '--disable-dom' '--disable-fileinfo'  '--disable-json' '--disable-intl' '--disable-pdo' '--disable-phar'  '--disable-posix' '--disable-soap' '--disable-sockets'  '--disable-sysvsem' '--disable-sysvshm' '--disable-sysvmsg'  '--disable-wddx' '--disable-xmlreader' '--disable-xmlwriter'  '--disable-zip' '--without-gd' '--without-imap' '--without-xmlrpc'  '--without-xsl' '--without-ldap' '--without-pgsql' '--without-snmp'  '--without-mcrypt' '--without-tidy' '--without-enchant'  '--without-recode' '--without-mssql' '--without-pspell'  '--without-unixODBC' 'build_alias=x86_64-redhat-linux-gnu'  'host_alias=x86_64-redhat-linux-gnu'  'target_alias=x86_64-redhat-linux-gnu' 'CFLAGS=-O2 -g -pipe -Wall  -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong  --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic  -fno-strict-aliasing -Wno-pointer-sign' 'CXXFLAGS=-O2 -g -pipe -Wall  -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong  --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic'
-- | --

LINUX: 
  | Linux 3.10.0-962.3.2.lve1.5.26.1.el7.x86_64 #1 SMP Fri Jun 28 06:30:57 EDT 2019 x86_64
-- | --

OpenSSL support | enabled
-- | --
OpenSSL Library Version | OpenSSL 1.0.2k-fips  26 Jan 2017
OpenSSL Header Version | OpenSSL 1.0.2k  26 Jan 2017
Openssl default config | /opt/alt/openssl/etc/pki/tls/openssl.cnf

PDO Driver for Snowflake | enabled
-- | --
Version | 0.2.1

Directive | Local Value | Master Value
-- | -- | --
pdo_snowflake.cacert | /etc/pki/tls/certs/ca-bundle.crt | /etc/pki/tls/certs/ca-bundle.crt
pdo_snowflake.debug | no value | no value
pdo_snowflake.logdir | no value | no value
pdo_snowflake.loglevel | no value | no value

why do I get an OPENSSL error?  Please help.
Thanks,
Dan

**Comment by dlinstedt** [comment]
My web-host provided the following information about this:  Specifically related to CLOUD LINUX.  If the developers have advice on "setting the OPEN SSL version" in the make process, that would be very helpful at this point? 
-------------
Thanks for reaching out. I have taken a look and I believe this issue is due to the fact that the CloudLinux PHP handlers use their own version of OpenSSL separate from the primary OpenSSL installed on the server. With CloudLinux the OpenSSL library used by PHP packages is located under /opt/alt/openssl, but looking at the configure script for pdo_snowflake there doesn't appear to be a way to define a custom path for the OpenSSL libraries when building the extension.

Unfortunately you may need to reach out to the developer of the pdo_snowflake extension and see if they can add support for specifying a custom OpenSSL path.

**Comment by smtakeda** [comment]
As of today, OpenSSL 1.1.1b is statically linked for pdo_snowflake, and we don't have a plan to allow the users to change the dependency.

**Comment by dlinstedt** [comment]
Hi Shige,  Thank you for responding. I appreciate your feedback.  Dan
