### ISSUE TITLE
undefined symbol: OpenSSL_version_num

### ISSUE THREAD

**Issue by humanier** [snowflakedb/pdo_snowflake#196]
Started to get this message in Ubuntu 16.04 based container after rebuilding it today (it was working fine before). Container build included `apt update/upgrade`. 

The following error is shown on every attempt to run any PHP command (e.g. `php --version`)
`php: symbol lookup error: /usr/lib/php/20151012/pdo_snowflake.so: undefined symbol: OpenSSL_version_num
`
OpenSSL version is 1.0.2g (which seems to be the highest available from official APT repo for Ubuntu 16.04). 

The symbol seems to be only defined since OpenSSL 1.1.0 -  https://www.openssl.org/docs/man1.0.2/man3/OPENSSL_VERSION_NUMBER.html

What could be possible workarounds/fixes except jumping to Ubuntu 18?

**Comment by notkriswagner** [comment]
@humanier Are you using the provided scripts to build the PDO Snowflake driver? We bundle an updated version of OpenSSL with the driver since we need that newer version for the OCSP check that we do in cURL. If you are building the PDO Driver with the system OpenSSL then that error is expected

**Comment by humanier** [comment]
Thanks for reply. Should I do anything special to avoid building PDO driver with system OpenSSL? So far I have been just following instructions from readme.md:
`export PHP_HOME=/usr
git clone https://github.com/snowflakedb/pdo_snowflake.git
cd pdo_snowflake
./scripts/build_pdo_snowflake.sh`

**Comment by notkriswagner** [comment]
What version of PHP are you using? That sequence of steps that you outlined should work and is what we do in our CI pipeline (which is currently green). If you can post the output from that build step, that might help me identify what is wrong

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
