### ISSUE TITLE
Feature request: named placeholders

### ISSUE THREAD

**Issue by zoltan-fedor** [snowflakedb/pdo_snowflake#201]
Hi,
I have seen in the README (https://github.com/snowflakedb/pdo_snowflake#limitations) and also in https://github.com/snowflakedb/pdo_snowflake/pull/159 that the named placeholders are currently not supported.

Could this be added please?

We are doing a migration to Snowflake with lots of legacy code which we would need to majorly rewrite to switch from named placeholders to positional ones.

Thanks

**Comment by notkriswagner** [comment]
Hi @zoltan-fedor ,

This feature request is already requested in issue #68 . Closing since this is a duplicate
