### ISSUE TITLE
Unexplicable "hanging" when assigning Snowflake object to associative array

### ISSUE THREAD

**Issue by zoltan-fedor** [snowflakedb/pdo_snowflake#202]
I am facing something really weird related to the Snowflake PDO module.
We have a legacy PHP application which connects to multiple databases, Oracle, MySQL and now I am trying to add Snowflake.
For each we wrote a db object and assign the connection to an associative array. It works great for Oracle and MySQL, but not for Snowflake.

Take a look at the below example.
The section marked with "# this works" works, but the one marked with "# this hangs" will hang.
The only difference between the two that the object is assigned to an associative array instead of a variable.
Any idea what might be causing this?
Again, doing the same assignment with the MySQL PDO driver is no problem, nor with the OCI driver for Oracle.

```
<?php
class db_snowflake
{
        public $account;
	public $login;
	public $password;
	public $http_proxy;
	public $https_proxy;

	function __construct($account, $login, $password, $http_proxy, $https_proxy)
	{
	  $this->dbaccount = $account;
	  $this->dbuser = $login;
	  $this->dbpass = $password;
	  $this->dbhttp_proxy = $http_proxy;
	  $this->dbhttps_proxy = $https_proxy;
	}
    
	public function connect() 
	{
          # set the proxy env variable, so Snowflake knows how to connect to the internet
	  putenv("http_proxy=".$this->dbhttp_proxy);
	  putenv("https_proxy=".$this->dbhttps_proxy);
        
          $dsn = "snowflake:account=".$this->dbaccount;
        
          try {
            $this->dbh = new PDO($dsn, $this->dbuser, $this->dbpass);
	    $this->dbh->setAttribute( PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION );
          } catch (Exception $e) {
            error_log($e->getMessage());
            exit('Something weird happened with the data warehouse connection...');
          }
       }
}


# this works:
$c = new db_snowflake("myaccount",
                      "myuser",
                      "mypassword",
                      "http://ourproxy:80",
                      "http://ourproxy:80");
$c->connect();

# this hangs:
$d['conn1'] = new db_snowflake("myaccount",
                               "myuser",
                               "mypassword",
                               "http://ourproxy:80",
                               "http://ourproxy:80");
$d['conn1']->connect();

?>
```

PHP version: 7.1

**Comment by notkriswagner** [comment]
Hi @zoltan-fedor ,

I'm not sure why that would cause the connection to hang. Out of curiosity, what if you did the following:

```
$c = new db_snowflake("myaccount",
                      "myuser",
                      "mypassword",
                      "http://ourproxy:80",
                      "http://ourproxy:80");
$c->connect();
$d['conn1'] = $c;
```

Are you able to use the connection from that point on?

**Comment by zoltan-fedor** [comment]
Unfortunately this hangs too:

```
$c = new db_snowflake("myaccount",
                      "myuser",
                      "mypassword",
                      "http://ourproxy:80",
                      "http://ourproxy:80");
$c->connect();
$d['conn1'] = $c;
```

If the last line is not included, then it runs fine.
Very mysterious...

**Comment by zoltan-fedor** [comment]
Any ideas?
I hit the exact same with PHP 7.2 and the newest codebase.

**Comment by zoltan-fedor** [comment]
Actually it turns out the the PDO object doesn't need to be assigned to an associate array, it can be assigned to anything to get this "hanging". What is important, that it needs to be reassigned to a new variable.
Below are the different scenarios:

FAST: No reassignment of the PDO object:
```
putenv("http_proxy=http://ourproxy:80");
putenv("https_proxy=http://ourproxy:80");

$pdo = new PDO("snowflake:account=myacount;", "myuser", "mypassword");
print(gettype($pdo));
>> it prints: 'object'
```

HANGS: PDO object is re-assigned (it hangs for about 5 mins before eventually continuing):
```
putenv("http_proxy=http://ourproxy:80");
putenv("https_proxy=http://ourproxy:80");

$pdo = new PDO("snowflake:account=myacount;", "myuser", "mypassword");
$d = $pdo;  // <= THIS LINE WAS ADDED
print(gettype($pdo));
>> it eventually prints: 'object'
```

HANGS: PDO object is re-assigned as reference (it hangs for about 5 mins before eventually continuing):
```
putenv("http_proxy=http://ourproxy:80");
putenv("https_proxy=http://ourproxy:80");

$pdo = new PDO("snowflake:account=myacount;", "myuser", "mypassword");
$d = &$pdo;  // <= THIS LINE WAS ADDED
print(gettype($pdo));
>> it eventually prints: 'object'
```

**Comment by zoltan-fedor** [comment]
I am not quite sure why, but adding an additional statement at the end of the script to empty out the $pdo variable solves the whole hanging issue

THIS IS NOW FAST:
```
putenv("http_proxy=http://ourproxy:80");
putenv("https_proxy=http://ourproxy:80");

$pdo = new PDO("snowflake:account=myacount;", "myuser", "mypassword");
$d = $pdo;
print(gettype($pdo));
$pdo = null;  // <- this line was added
>> it prints: 'object'
```

The idea came from looking at the documentation of the Snowflake PDO (see https://github.com/snowflakedb/pdo_snowflake#query) where I saw that they were "nulling" the PDO object at the end of the script. I didn't think that it will make a difference, but it did.

Also the PDO documentation suggest the closing out this way, see https://www.php.net/manual/en/pdo.connections.php

I am still not sure why if this last line is missing then it ONLY hangs if there was a reassignment of the PDO object, not otherwise...
