### ISSUE TITLE
OS

### ISSUE THREAD

**Issue by makkena6** [snowflakedb/pdo_snowflake#203]
Working

**Comment by makkena6** [comment]
I keep getting  error "Uncaught PDOException: could not find driver in /Applications/XAMPP/xamppfiles/htdocs" I did update the ini file in XAMP with below. What else am I missing ?


/opt/snowflake/snowflakeodbc/lib/universal/libSnowflake.dylib
extension=php_pdo_snowflake.dll
extension=pdo_snowflake.so
extension=modules/pdo_snowflake.so
extension=php_pdo_snowflake.dll
extension=pdo_snowflake.so
extension=modules/pdo_snowflake.so

**Comment by notkriswagner** [comment]
I haven't used XAMP or tested the driver with XAMP, but the ini properties should be the same as they are in Linux.

**Comment by makkena6** [comment]
thank you, i think the issue is i am missing .so file. I will follow the same instructions in your Linux guide and create pdo_snowflake.so file so that i can reference it and try again.

**Comment by makkena6** [comment]
trying to create the new pdo file now and i keep getting stuck here

grep: /usr/include/php/main/php.h: No such file or directory
grep: /usr/include/php/Zend/zend_modules.h: No such file or directory
grep: /usr/include/php/Zend/zend_extensions.h: No such file or directory
Configuring for:
PHP Api Version:        
Zend Module Api No:     
Zend Extension Api No:  
Cannot find autoconf. Please check your autoconf installation and the

**Comment by makkena6** [comment]
one more error after i fixed autoconf

pdo_snowflake/pdo_snowflake.c:9:10: fatal error: 'php.h' file not found
#include "php.h"

**Comment by notkriswagner** [comment]
This suggests that your PHP environment on your mac is not properly setup

**Comment by makkena6** [comment]
do i need to reinstall PHP or anything in particular?

**Comment by notkriswagner** [comment]
Its seems like you're missing the dev packages from your PHP install. You could try reinstalling or build PHP on your mac. Here are the instructions that I followed to build PHP: https://mac-dev-env.patrickbougie.com/php/

**Comment by makkena6** [comment]
This really helped. I was finally able to generate the pdo_snowflake.so. In my PHP.ini file i just referenced below. Still getting PDO error, anything else missing. I am really close now.
extension=pdo_snowflake.so

**Comment by makkena6** [comment]
My PHP code is this

<?php
$dsn = "SNOWFLAKE";
$account = "xxxy";
$user = "abc";
$password = "123dcf!";
$dbh = new PDO("snowflake:account=$account", $user, $password);
$dbh->setAttribute( PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION );
echo "Connected\n";
$sth = $dbh->query("select 1234");
while ($row=$sth->fetch(PDO::FETCH_NUM)) {
    echo "RESULT: " . $row[0] . "\n";
}
$dbh = null;
echo "OK\n";

?>

**Comment by makkena6** [comment]
$dsn = "aaa";
$account = "aasa";
$user = "asda";
$password = "dss12!";
$dbh = new PDO("snowflake:account=$account", $user, $password);
$dbh->setAttribute( PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION );
echo "Connected\n";
$sth = $dbh->query("select 1234");
while ($row=$sth->fetch(PDO::FETCH_NUM)) {
    echo "RESULT: " . $row[0] . "\n";
}
$dbh = null;
echo "OK\n";

**Comment by notkriswagner** [comment]
What line in your PHP code example are you getting the error at? And what is the exact error that you are encountering?

**Comment by makkena6** [comment]
it is this one $dbh = new PDO("snowflake:account=$account", $user, $password);

**Comment by makkena6** [comment]
Stack trace: #0 {main} thrown

**Comment by notkriswagner** [comment]
@makkena6 Is that the whole error stack?

**Comment by makkena6** [comment]
Yeah that is the error. Does not give any other info.

**Comment by makkena6** [comment]
this usually happens when it does not recognize the function  i think it doe not understand "new PDO"

**Comment by makkena6** [comment]
PDO->__construct('snowflake:accou...', 'xyz', 'sd123!') #1 {main} thrown in

**Comment by makkena6** [comment]
Fatal error: Uncaught PDOException: could not find driver in /Applications/XAMPP/xamppfiles/htdocs/extensions-api-master/myextensions/TAB/PHP/Snowflake.php:6 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/extensions-api-master/myextensions/TAB/PHP/Snowflake.php(6): PDO->__construct('snowflake:accou...', 'aaa', 'aaa123') #1 {main} thrown in /Applications/XAMPP/xamppfiles/htdocs/extensions-api-master/myextensions/TAB/PHP/Snowflake.php on line 6

**Comment by notkriswagner** [comment]
What happens when you run this command:

`$PHP_HOME/bin/php -dextension=modules/pdo_snowflake.so -m | grep pdo_snowflake`

But with `$PHP_HOME/bin/php` replaced by the path to your php executable

**Comment by makkena6** [comment]
i get this 
"Unable to load dynamic library 'modules/pdo_snowflake.so' - dlopen(modules/pdo_snowflake.so, 0x0009): code signature in (modules/pdo_snowflake.so) not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed. in Unknown on line 0"

**Comment by notkriswagner** [comment]
Whats the php version?

**Comment by makkena6** [comment]
7.1.23

**Comment by notkriswagner** [comment]
@makkena6 try turning off System Integrity Protection on your mac and then test (and then turn System Integrity Protection back on if you so desire). This was added in Mojave and is most likely the culprit behind this issue

**Comment by makkena6** [comment]
thanks a lot for help, let me try and will update you as it requires restart

**Comment by makkena6** [comment]
Update when i run this command now php -dextension=modules/pdo_snowflake.so -m | grep pdo_snowflake i get blow which i assume no issue with PDO

pdo_snowflake

**Comment by makkena6** [comment]
the issue could be in my INI file now? in my php.ini i have enabled this below

extension=pdo_snowflake.so

Do i need to add actual pdo_snowlfake.so any where ?

**Comment by makkena6** [comment]
when i run this it also works
 $ php -i | grep -i "pdo support"
PDO support => enabled

 but php sample code has same issue

**Comment by makkena6** [comment]
i think issue is with ini file, do i change the PHP.ini-production?  with extension=pdo_snowflake.so

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
