### ISSUE TITLE
undefined symbol: pdo_sf_param_store_get

### ISSUE THREAD

**Issue by zoltan-fedor** [snowflakedb/pdo_snowflake#208]
Unfortunately since commit https://github.com/snowflakedb/pdo_snowflake/pull/204/commits/d0d78076cc4a0829ec5f55865eb4ab458995f1db the library doens't load with `undefined symbol: pdo_sf_param_store_get` error using PHP 7.2.

See full error below:
`PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_snowflake.so' (tried: /opt/remi/php72/root/usr/lib64/php/modules/pdo_snowflake.so (/opt/remi/php72/root/usr/lib64/php/modules/pdo_snowflake.so: undefined symbol: pdo_sf_param_store_get), /opt/remi/php72/root/usr/lib64/php/modules/pdo_snowflake.so.so (/opt/remi/php72/root/usr/lib64/php/modules/pdo_snowflake.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0`

**Comment by zoltan-fedor** [comment]
Ignore.
This happened because I have applied this fix (https://github.com/snowflakedb/pdo_snowflake/issues/198) without rewriting it to include the new `snowflake_paramstore.o` file.

**Comment by notkriswagner** [comment]
@zoltan-fedor What's the OS and platform you are using to test this?

**Comment by zoltan-fedor** [comment]
@notkriswagner, Thanks. It is RedHat 7.5, PHP7.2, but as I wrote above, this was my error.
I was using the fix from #198 and forgot to modify that fix (manual linking) for the new `snowflake_paramstore.o` file, which is why I had this `undefined symbol` error.
Please ignore.
