### ISSUE TITLE
Filters using bind variables returning 0 results with PHP PDO driver

### ISSUE THREAD

**Issue by sfc-gh-mjain** [snowflakedb/pdo_snowflake#211]
Account: AWS-US-East-NC10487
Region: VA
Reproducable: Yes

One of the customer is trying to run a query using PHP PDO driver and is getting 0 results back. The query has bind variables.
Same query when run through UI and bind variables being replaced with actual values, returns 22 rows.

I tried to rerun the queries and was able to see the same behavior

Replicated customer driver query: 018de115-00e8-b66b-0000-0004011591ea

UI query replacing the bind variables: 018de117-004e-d1d9-0000-00040115925a

Driver logs are attached:
[snowflake_20190730214243.txt](https://github.com/snowflakedb/pdo_snowflake/files/4033189/snowflake_20190730214243.txt)

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
