### ISSUE TITLE
Segmentationfault when using `TRACE` as log level

### ISSUE THREAD

**Issue by hcira** [snowflakedb/pdo_snowflake#212]
The SegFault is generated by `vfprintf` (I guess when writing log), some trace:
`(gdb) bt
#0  0x00007fd384151099 in vfprintf () from /lib64/libc.so.6
#1  0x00007fd36f8fc44f in log_log_va_list (level=24, file=0x7ffffff5 <Address 0x7ffffff5 out of bounds>, line=1668212600,
    ns=0xffffffffffffffff <Address 0xffffffffffffffff out of bounds>, fmt=0x0, args=0x7fd3841512ed <vfprintf+19661>,
    args@entry=0x7ffd636ee698) at /home/vagrant/libsnowflakeclient/lib/logger.c:145
#2  0x00007fd36f8fc5b8 in log_log (level=level@entry=1, file=file@entry=0x7fd36fb2a538 "/tmp/pdo_snowflake/snowflake_stmt.c",
    line=line@entry=402, ns=ns@entry=0x7fd36fb2a18a "PDO",
    fmt=fmt@entry=0x7fd36fb2a5d0 "paramno: %ld, name: %s, max_len: %ld, type: %s, value: %p")
    at /home/vagrant/libsnowflakeclient/lib/logger.c:98
#3  0x00007fd36f8f0cb7 in pdo_snowflake_stmt_param_hook (stmt=<optimized out>, param=0x7fd35d1725f0, event_type=PDO_PARAM_EVT_ALLOC)
    at /tmp/pdo_snowflake/snowflake_stmt.c:397
#4  0x00007fd373f4e6fe in really_register_bound_param (param=param@entry=0x7ffd636ee890, stmt=stmt@entry=0x7fd37d87f880,
    is_param=is_param@entry=1) at /usr/src/debug/php-7.1.33/ext/pdo/pdo_stmt.c:409
#5  0x00007fd373f4edbb in register_bound_param (stmt=0x7fd37d87f880, is_param=is_param@entry=1, return_value=0x7ffd636ee940,
    execute_data=<optimized out>) at /usr/src/debug/php-7.1.33/ext/pdo/pdo_stmt.c:1565
#6  0x00007fd373f4eef4 in zim_PDOStatement_bindParam (execute_data=<optimized out>, return_value=0x7ffd636ee940)
    at /usr/src/debug/php-7.1.33/ext/pdo/pdo_stmt.c:1620
#7  0x00007fd37f6a3b96 in ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER () at /usr/src/debug/php-7.1.33/Zend/zend_vm_execute.h:970
#8  0x00007fd37f65274b in execute_ex (ex=<optimized out>) at /usr/src/debug/php-7.1.33/Zend/zend_vm_execute.h:429
#9  0x00007fd37f5fd9c1 in zend_call_function (fci=fci@entry=0x7ffd636eeae0, fci_cache=fci_cache@entry=0x7ffd636eeab0)
    at /usr/src/debug/php-7.1.33/Zend/zend_execute_API.c:855
#10 0x00007fd37f54c75f in zif_call_user_func (execute_data=<optimized out>, return_value=0x7fd37d811fd0)
    at /usr/src/debug/php-7.1.33/ext/standard/basic_functions.c:4869
#11 0x00007fd37f6a2cad in ZEND_DO_FCALL_BY_NAME_SPEC_RETVAL_USED_HANDLER () at /usr/src/debug/php-7.1.33/Zend/zend_vm_execute.h:876
#12 0x00007fd37f65274b in execute_ex (ex=<optimized out>) at /usr/src/debug/php-7.1.33/Zend/zend_vm_execute.h:429
#13 0x00007fd37f5fd9c1 in zend_call_function (fci=fci@entry=0x7ffd636eece0, fci_cache=fci_cache@entry=0x7ffd636eecb0)
---Type <return> to continue, or q <return> to quit---
    at /usr/src/debug/php-7.1.33/Zend/zend_execute_API.c:855
#14 0x00007fd37f54c94d in zif_call_user_func_array (execute_data=0x7fd37d8119b0, return_value=0x7fd37d811970)
    at /usr/src/debug/php-7.1.33/ext/standard/basic_functions.c:4895
#15 0x00007fd37f6a2cad in ZEND_DO_FCALL_BY_NAME_SPEC_RETVAL_USED_HANDLER () at /usr/src/debug/php-7.1.33/Zend/zend_vm_execute.h:876
#16 0x00007fd37f65274b in execute_ex (ex=<optimized out>) at /usr/src/debug/php-7.1.33/Zend/zend_vm_execute.h:429
#17 0x00007fd37f5fd9c1 in zend_call_function (fci=fci@entry=0x7ffd636eeef0, fci_cache=fci_cache@entry=0x7ffd636eeec0)
    at /usr/src/debug/php-7.1.33/Zend/zend_execute_API.c:855
#18 0x00007fd37f54c75f in zif_call_user_func (execute_data=<optimized out>, return_value=0x7fd37d811850)
    at /usr/src/debug/php-7.1.33/ext/standard/basic_functions.c:4869
#19 0x00007fd37f6a2cad in ZEND_DO_FCALL_BY_NAME_SPEC_RETVAL_USED_HANDLER () at /usr/src/debug/php-7.1.33/Zend/zend_vm_execute.h:876
#20 0x00007fd37f65274b in execute_ex (ex=<optimized out>) at /usr/src/debug/php-7.1.33/Zend/zend_vm_execute.h:429
#21 0x00007fd37f5fd9c1 in zend_call_function (fci=fci@entry=0x7ffd636ef0f0, fci_cache=fci_cache@entry=0x7ffd636ef0c0)
    at /usr/src/debug/php-7.1.33/Zend/zend_execute_API.c:855
#22 0x00007fd37f54c94d in zif_call_user_func_array (execute_data=0x7fd37d811680, return_value=0x7fd37d811640)
    at /usr/src/debug/php-7.1.33/ext/standard/basic_functions.c:4895
#23 0x00007fd37f6a2cad in ZEND_DO_FCALL_BY_NAME_SPEC_RETVAL_USED_HANDLER () at /usr/src/debug/php-7.1.33/Zend/zend_vm_execute.h:876
#24 0x00007fd37f65274b in execute_ex (ex=<optimized out>) at /usr/src/debug/php-7.1.33/Zend/zend_vm_execute.h:429
#25 0x00007fd37f5fd9c1 in zend_call_function (fci=fci@entry=0x7ffd636ef300, fci_cache=fci_cache@entry=0x7ffd636ef2d0)
    at /usr/src/debug/php-7.1.33/Zend/zend_execute_API.c:855
#26 0x00007fd37f54c75f in zif_call_user_func (execute_data=<optimized out>, return_value=0x7fd37d811520)
    at /usr/src/debug/php-7.1.33/ext/standard/basic_functions.c:4869
#27 0x00007fd37f6a2cad in ZEND_DO_FCALL_BY_NAME_SPEC_RETVAL_USED_HANDLER () at /usr/src/debug/php-7.1.33/Zend/zend_vm_execute.h:876
#28 0x00007fd37f65274b in execute_ex (ex=<optimized out>) at /usr/src/debug/php-7.1.33/Zend/zend_vm_execute.h:429
#29 0x00007fd37f6a58e4 in zend_execute (op_array=0x7fd37d880000, op_array@entry=0x7fd365a16fb8,
    return_value=return_value@entry=0x7fd37d811480) at /usr/src/debug/php-7.1.33/Zend/zend_vm_execute.h:474
---Type <return> to continue, or q <return> to quit---
#30 0x00007fd37f60d1d4 in zend_execute_scripts (type=type@entry=8, retval=0x7fd37d811480, retval@entry=0x0,
    file_count=file_count@entry=3) at /usr/src/debug/php-7.1.33/Zend/zend.c:1482
#31 0x00007fd37f5acef8 in php_execute_script (primary_file=primary_file@entry=0x7ffd636f16f0)
    at /usr/src/debug/php-7.1.33/main/main.c:2577
#32 0x00007fd37f6a784a in php_handler (r=<optimized out>) at /usr/src/debug/php-7.1.33/sapi/apache2handler/sapi_apache2.c:712
#33 0x000056411d249c40 in ap_run_handler (r=r@entry=0x56411f555260) at config.c:170
#34 0x000056411d24a189 in ap_invoke_handler (r=r@entry=0x56411f555260) at config.c:444
#35 0x000056411d25f69c in ap_internal_redirect (new_uri=<optimized out>, r=<optimized out>) at http_request.c:791
#36 0x00007fd37e308f6c in handler_redirect (r=0x56411f2975f0) at mod_rewrite.c:5259
#37 0x000056411d249c40 in ap_run_handler (r=r@entry=0x56411f2975f0) at config.c:170
#38 0x000056411d24a189 in ap_invoke_handler (r=r@entry=0x56411f2975f0) at config.c:444
#39 0x000056411d26037a in ap_process_async_request (r=0x56411f2975f0) at http_request.c:453
#40 0x000056411d26064e in ap_process_request (r=r@entry=0x56411f2975f0) at http_request.c:488
#41 0x000056411d25c715 in ap_process_http_sync_connection (c=0x56411f263530) at http_core.c:214
#42 ap_process_http_connection (c=0x56411f263530) at http_core.c:255
#43 0x000056411d253800 in ap_run_process_connection (c=c@entry=0x56411f263530) at connection.c:42
#44 0x000056411d253d58 in ap_process_connection (c=c@entry=0x56411f263530, csd=<optimized out>) at connection.c:219
#45 0x00007fd37fc009d9 in child_main (child_num_arg=child_num_arg@entry=27, child_bucket=child_bucket@entry=0) at prefork.c:615
#46 0x00007fd37fc00c20 in make_child (s=0x56411ee363e0, slot=27) at prefork.c:717
#47 0x00007fd37fc01a26 in perform_idle_server_maintenance (p=<optimized out>) at prefork.c:821
#48 prefork_run (_pconf=<optimized out>, plog=<optimized out>, s=<optimized out>) at prefork.c:1014
#49 0x000056411d22ba2e in ap_run_mpm (pconf=pconf@entry=0x56411ee0d138, plog=0x56411ee3a358, s=0x56411ee363e0) at mpm_common.c:94
#50 0x000056411d223fd9 in main (argc=1, argv=0x7ffd636f1e68) at main.c:819`
Can you please have a look into it? thanks!

**Comment by notkriswagner** [comment]
Adding to our issue backlog

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
