### ISSUE TITLE
Exceeding 1,000 files on import does not return any error

### ISSUE THREAD

**Issue by nalvest** [snowflakedb/pdo_snowflake#213]
If you run a Copy Into query from a stage that imports more than 1,000 files - it will returns an error: "The number of files exceeds the 1,000 limit.".  This error is only visible through the online user interface.

Through the PHP PDO Driver - it's not return any error. ErrorInfo returned as successful. The result set returned is empty and the error info shows no errors.

We need to have a proper error message returned so that we can handle it on our side.

**Comment by notkriswagner** [comment]
Adding to our issue backlog

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
