### ISSUE TITLE
Arrow format support - feature request

### ISSUE THREAD

**Issue by zoltan-fedor** [snowflakedb/pdo_snowflake#214]
It would be nice if we could get the Arrow format support added just like it has been for the latest JDBC and Python drivers.
The performance improvement on fetching speed would be great.

See https://www.snowflake.com/blog/fetching-query-results-from-snowflake-just-got-a-lot-faster-with-apache-arrow/

**Comment by notkriswagner** [comment]
This is already in our backlog, but right now there is no ETA for implementation

**Comment by zoltan-fedor** [comment]
Hi @notkriswagner, thanks for the update. We are eagerly waiting... :-)
