### ISSUE TITLE
Aborting queries where the PHP script gets aborted

### ISSUE THREAD

**Issue by zoltan-fedor** [snowflakedb/pdo_snowflake#216]
Hey,
I am using this PDO library with Apache and trying to get the queries aborted when the PHP call is cancelled.

I have set `ALTER SESSION SET ABORT_DETACHED_QUERY = TRUE` to no avail.

Any other ideas?

**Comment by notkriswagner** [comment]
@zoltan-fedor let me try to reproduce this. Just to confirm, you're running a PHP script that is executing the query and then you kill the script (i.e. ctrl+c on the command line) and the query is not cancelled on the server-side?

**Comment by zoltan-fedor** [comment]
@notkriswagner,
Thanks. I have actually never tested by killing a PHP script. No, I have Apache - PHP 7.2 (mod_php7) and when http calls which execute a Snowflake query get cancelled, the Snowflake query runs to completion instead of aborting even with `ALTER SESSION SET ABORT_DETACHED_QUE = TRUE`

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
