### ISSUE TITLE
SNOW-256743: Where does ./scripts/build_pdo_snowflake.sh put pdo_snowflake.so on OSX?

### ISSUE THREAD

**Issue by carcinocron** [snowflakedb/pdo_snowflake#239]
I was thinking I could manually move it to /usr/local/lib/php/pecl/20170718/pdo_snowflake.so to fix the issue everyone else is having:
```
PHP Warning:  PHP Startup: Unable to load dynamic library 'modules/pdo_snowflake.so' (tried: modules/pdo_snowflake.so (dlopen(modules/pdo_snowflake.so, 9): image not found), /usr/local/lib/php/pecl/20170718/modules/pdo_snowflake.so.so (dlopen(/usr/local/lib/php/pecl/20170718/modules/pdo_snowflake.so.so, 9): image not found)) in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'modules/pdo_snowflake.so' (tried: modules/pdo_snowflake.so (dlopen(modules/pdo_snowflake.so, 9): image not found), /usr/local/lib/php/pecl/20170718/modules/pdo_snowflake.so.so (dlopen(/usr/local/lib/php/pecl/20170718/modules/pdo_snowflake.so.so, 9): image not found)) in Unknown on line 0
```
but I can't find the file after running ./scripts/build_pdo_snowflake.sh

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
