### ISSUE TITLE
SNOW-257897: Create a new release with the fix for linux.

### ISSUE THREAD

**Issue by ronaldfenner** [snowflakedb/pdo_snowflake#240]
I pulled the GA Release only to build and find it was broken on linux because of the undefined symbol bug that has been fixed. I ended up having to pull the current master head with it so i could build a working version. It'd be nice to go ahead and do a new 1.0.1 release with it for people who come and just download the release. 
I try to stay on official releases when building automated scripts to install the packages in server images.

**Comment by sfc-gh-kwagner** [comment]
Hi @ronaldfenner , we released v1.0.1 a week ago. Let me know if that fixes your issue!

**Comment by ronaldfenner** [comment]
Thanks,
I  integrated the release into the build and was able to load it with no problems and run queries with it.

Ronald Fenner
Network Architect
Game Circus LLC.

rfenner@gamecircus.com
