### ISSUE TITLE
SNOW-271529: php_pdo_snowflake.dll file not being picked up by php.ini

### ISSUE THREAD

**Issue by Heisenberg87** [snowflakedb/pdo_snowflake#243]
I have followed the github instructions to build the dll file for windows and unable to get the php ini file to pick up the dll file. 

I have added the php_pdo_snowflake.dll to the 'ext' folder found in my xampp installation 

Files copied to the following locations : 
DLL : "C:\xampp\php\php-7.4.13\ext" 
cacert = "C:\xampp\php\php-7.4.13"

These have been added to php ini 

extension=php_pdo_snowflake.dll
pdo_snowflake.cacert=C:\xampp\php\php-7.4.13\cacert.pem

I am also presented with the following error with the PHP cli

PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_snowflake' (tried: ext\pdo_snowflake (The specified module could not be found.), ext\php_pdo_snowflake.dll (The specified module could not be found.)) in Unknown on line 0      PHP 7.4.13 (cli) (built: Nov 24 2020 12:43:30) ( NTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
