### ISSUE TITLE
SNOW-411534: Failed to Build on MacBook Pro M1 Silicon 2021

### ISSUE THREAD

**Issue by sonicsleuth** [snowflakedb/pdo_snowflake#251]
Getting the following error when building Snowflake PDO in a Docker Container.  

```
executor failed running [/bin/sh -c ./scripts/build_pdo_snowflake.sh]: exit code: 2
ERROR: Service 'app' failed to build : Build failed
```

This issue appears only to be happening on Mac M1 Silicon chipsets as the container builds fine on Mac Intel, Windows, Linux, and Production Ubuntu.  If we remove Snowflake from the Docker Container, the container builds fine. Thus, the bug appears to be in the above script.

**Comment by sonicsleuth** [comment]
Could this issue be related to the use of Mac M1 using the linux/arm64 architecture? I read other posts how Docker cannot build the MySQL container locally due to MySQL does not support linux/arm64 at this time.

**Comment by sfc-gh-kterada** [comment]
We are looking into ARM support in the future but it is not supported at this time.

**Comment by sfc-gh-hkapre** [comment]
Closing. This was added to our backlog but we don't yet have a plan for ARM support

**Comment by slashrsm** [comment]
Any progress on this? While this is not such a big issue in server environments it is becoming more so with more and more developers working on M1-based machines.

**Comment by rolandsusans** [comment]
Yes, the same thing as for @slashrsm.
I'm also looking forward to `linux/arm64` ( M1 ) support.

**Comment by kissifrot** [comment]
Hello there, also looking for ARM64 support for AWS instances (Graviton 2/3) :pray:
