### ISSUE TITLE
[MAC (non-M1)] Idiot-proofing: 20-pdo_snowflake.ini was not loading

### ISSUE THREAD

**Issue by GT-SiRe** [snowflakedb/pdo_snowflake#252]
I just want to drop a comment that I was encountering the error message:

`SQLSTATE[08001] [240012] curl_easy_perform() failed: SSL peer certificate or SSH remote key was not OK
`

despite following the instructions in the readme very carefully. It seems this was happening because the cacert.pem was not being loaded in the 20-pdo_snowflake.ini file. Took me way too long to realize this was happening. 

Using version 7.2.34 of PHP, installed with Brew locally on a Mac (11.3.1 Big Sur) and in an app using Lumen framework. 

**TL;DR:**
_I added the lines from the 20-pdo_snowflake.ini example file to the php.ini itself, and the driver started working!_ 

Would love to understand what mechanism is supposed to be in place (php itself? nginx? other?) to even attempt to ingest that 20-pdo_snowflake.ini file, I do not know what is expected to ensure those config value are being brought into PHP. Is my environment a unique snowflake (ha!) in that it was not even recognizing or using that ini file despite it being present in the correct directory *and* set to 777 for perms? I'm genuinely asking - would love to learns something new here about how these configs work. 

If it isn't a universal mechanism that ingests this config file, I'd love to see an update to the readme to ensure that others don't fall into this same trap/have this same issue. 

Edit: This is also tested and *working* with PHP7.4 (in case the reader thinks it might be impossible, it's not!)

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
