### ISSUE TITLE
Error in Build steps on Ubuntu 20.04/PHP 7.4

### ISSUE THREAD

**Issue by jqr108** [snowflakedb/pdo_snowflake#258]
Working off of a fresh EC2 with Ubuntu 20.04, PHP 7.4 already installed.

I see phpize in /usr/bin

Followed the steps listed in the README
```
export PHP_HOME=/usr
git clone https://github.com/snowflakedb/pdo_snowflake.git
cd pdo_snowflake
./scripts/build_pdo_snowflake.sh
```

Is PHP_HOME=/usr correct for most all Ubuntu/PHP installs?
Does it matter where you clone the repo?

I'm getting the following warnings and errors from the build script:
```
*** Warning: Linking the shared library pdo_snowflake.la against the
*** static library libsnowflakeclient/lib/linux/libsnowflakeclient.a is not portable!
```
About 10 variations on that one. Then:

```
/usr/bin/ld: libsnowflakeclient/lib/linux/libsnowflakeclient.a(client.c.o): Relocations in generic ELF (EM: 62)
/usr/bin/ld: libsnowflakeclient/lib/linux/libsnowflakeclient.a(client.c.o): Relocations in generic ELF (EM: 62)
/usr/bin/ld: libsnowflakeclient/lib/linux/libsnowflakeclient.a: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
```

Anything I could be doing wrong here?

**Comment by egerb** [comment]
Have very similar, but can't build success with next error:
1. /usr//bin/ld: libsnowflakeclient/lib/linux/libsnowflakeclient.a: error adding symbols: file in wrong format
2. libtool: install: `./pdo_snowflake.la' is not a valid libtool archive

**Comment by luciifae** [comment]
Also running into the same issue here. Builds fine on a local VM running Ubuntu 20.04, but fails on my server which is also running Ubuntu 20.04. The only difference between the two is PHP installations, with my VM running 8.0 and my server running 8.1.

**Comment by sfc-gh-dszmolka** [comment]
(cleaning up old issues)
please make sure to consider [the prerequisites](https://github.com/snowflakedb/pdo_snowflake?tab=readme-ov-file#prerequisites) when building the `.so` 

marking this as closed for now but please do comment if it's still an issue
