### ISSUE TITLE
Failed compilation under php7.4

### ISSUE THREAD

**Issue by egerb** [snowflakedb/pdo_snowflake#260]
Failed compilation of lib with next errors:
1. /usr//bin/ld: libsnowflakeclient/lib/linux/libsnowflakeclient.a: error adding symbols: file in wrong format
2. libtool: install: `./pdo_snowflake.la' is not a valid libtool archive

Docker used.
OS version:
`PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"`

PHP version 7.4

**Comment by jeremymunozviarteix** [comment]
I have exactly the same problem, did you find a solution?

**Comment by egerb** [comment]
Still no solution, but will back to research in few days

**Comment by sfc-gh-dprzybysz** [comment]
PHP 7.x is not supported anymore
