### ISSUE TITLE
PHP Warning:  PHP Startup: Unable to load dynamic library 'modules/pdo_snowflake.so'

### ISSUE THREAD

**Issue by AmrAhmedArabyads** [snowflakedb/pdo_snowflake#264]
while running `$PHP_HOME/bin/php -dextension=modules/pdo_snowflake.so -m | grep pdo_snowflake`
got 
`PHP Warning:  PHP Startup: Unable to load dynamic library 'modules/pdo_snowflake.so' (tried: modules/pdo_snowflake.so (dlopen(modules/pdo_snowflake.so, 0x0009): dlopen(): file not found: modules/pdo_snowflake.so), /usr/lib/php/extensions/no-debug-non-zts-20180731/modules/pdo_snowflake.so.so (dlopen(/usr/lib/php/extensions/no-debug-non-zts-20180731/modules/pdo_snowflake.so.so, 0x0009): dlopen(): file not found: /usr/lib/php/extensions/no-debug-non-zts-20180731/modules/pdo_snowflake.so.so)) in Unknown on line 0`

my PHP version is **PHP 7.4.24** and mac os Big Sur

**Comment by gregcruce** [comment]
I am having the same issue. I had to go back to a Feb 2021 commit and recompile to get around this issue.

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
