### ISSUE TITLE
SNOW-538385: PDO not respects PDO::CASE_LOWER

### ISSUE THREAD

**Issue by DzmitryKom** [snowflakedb/pdo_snowflake#273]
Hi,
settings PDO::CASE_LOWER has no effect: 
$this->pdo->setAttribute(\PDO::ATTR_CASE , \PDO::CASE_LOWER);
and with \PDO::ATTR_DEFAULT_FETCH_MODE => \PDO::FETCH_ASSOC

array keys still comes in Upper case
Thanks

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
