### ISSUE TITLE
SNOW-541794: PHP Warning:  PHP Startup: pdo_snowflake: Unable to initialize module

### ISSUE THREAD

**Issue by AdrianPerry** [snowflakedb/pdo_snowflake#275]
while running `$PHP_HOME/bin/php -dextension=modules/pdo_snowflake.so -m | grep pdo_snowflake`
this is the output I got:
```
PHP Warning:  PHP Startup: pdo_snowflake: Unable to initialize module
Module compiled with module API=20170718
PHP    compiled with module API=20190902
These options need to match
 in Unknown on line 0
```

My PHP version is 7.4.27 and I am on Ubuntu 20.04. I am not sure what I am doing wrong, so any guidance on this problem is greatly appreciated.

**Comment by jonnylink** [comment]
Looks like the module was compiled with a different version of PHP.

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
