### ISSUE TITLE
SNOW-549427: Fatal error - Possible integer overflow in memory allocation (PUT)

### ISSUE THREAD

**Issue by felixcharvin** [snowflakedb/pdo_snowflake#276]
Hi,
I have the following error append when I use PUT command : 
**Fatal error: Possible integer overflow in memory allocation (18446744073709551615 * 16 + 0)**

I tried rebuild driver on windows and on linux system but it's the same for the 2 OS.

My PHP code is : 
$dbh->query("PUT 'file://A:/CODE/REPOS/BIM Data/Sources/public/Files/smallTest.json' @MYSTAGE;");

I tried to copy paste the query in SnowSQL and it works! So I think the error come from the driver.

This is on PHP 7.4 (Windows 10 or debian11), with the latest version of the PDO drivers.

Can you investigate on this please? It's really critical for us.
Thanks

**Comment by alexanderwburch** [comment]
Is there any fix or workaround here?

**Comment by sfc-gh-dszmolka** [comment]
hi - first of all, apologies for the lack of attention; we're changing that now.
second; is this still an issue? if so, please comment with the details (i.e. none of the `PUT` commands work, some of them don't work which involve specific files, etc. any details could help)
a reproduction code snippet would be probably very helpful too. thank you in advance !

**Comment by sfc-gh-dszmolka** [comment]
after syncing internally with the team, turns out `PUT` and `GET` not supported for this driver yet. It is not on the roadmap either for now. As a workaround, ODBC driver could be considered to use.

marking this issue as closed for now.
