### ISSUE TITLE
SNOW-604791: Support Key Pair Authentication

### ISSUE THREAD

**Issue by jcolfej** [snowflakedb/pdo_snowflake#283]
I didn't see anything in the documentation, I think it is not supported so I open a feature request.

Is it possible that the PHP module supports authentication by key instead of password?

This usage was recommended to me by Snowflake support.
See: https://docs.snowflake.com/en/user-guide/key-pair-auth.html

**Comment by sfc-gh-dszmolka** [comment]
(cleaning up old issues)
[this seems to be supported now](https://github.com/snowflakedb/pdo_snowflake?tab=readme-ov-file#using-key-pair-authentication)
