### ISSUE TITLE
SNOW-610053: Support for Ubuntu 20.04 / 22.04 in docker test

### ISSUE THREAD

**Issue by kissifrot** [snowflakedb/pdo_snowflake#284]
Hello,

Seems there is no current LTS version of Ubuntu docker images for tests, would it be possible to add support for it?

**Comment by sfc-gh-dszmolka** [comment]
Confirmed with the team: the dockerfiles in the repo are not being used in build/test and that's something left before we moving build/test to github runners 3 years ago.

Currently the build/test is run on ubuntu-latest https://github.com/snowflakedb/pdo_snowflake/blob/master/.github/workflows/build_test.yml#L119

Closing this issue.
