### ISSUE TITLE
Unable to build on Ubuntu 22.04 with PHP 8.1 

### ISSUE THREAD

**Issue by mrevjd** [snowflakedb/pdo_snowflake#300]
Followed the steps as per the README:
```
export PHP_HOME=/usr
git clone https://github.com/snowflakedb/pdo_snowflake.git
cd pdo_snowflake
./scripts/build_pdo_snowflake.sh
```
returns nothing.

If manually run phpize:
```
Configuring for:
PHP Api Version:         20210902
Zend Module Api No:      20210902
Zend Extension Api No:   420210902
configure.ac:22: warning: $as_echo is obsolete; use AS_ECHO(["message"]) instead
build/php.m4:2111: PHP_CONFIG_NICE is expanded from...
configure.ac:22: the top level
configure.ac:165: warning: The macro `AC_PROG_LIBTOOL' is obsolete.
configure.ac:165: You should run autoupdate.
build/libtool.m4:99: AC_PROG_LIBTOOL is expanded from...
configure.ac:165: the top level
```
./configure --enable-pdo_snowflake
Output
[pdo_snowflake_log.txt](https://github.com/snowflakedb/pdo_snowflake/files/10110259/pdo_snowflake_log.txt)

Then do make and make install

When I run my php script I see the follow console error:
`php: symbol lookup error: /usr/lib/php/20210902/pdo_snowflake.so: undefined symbol: SSL_get_peer_certificate`

Please let me know if you require more information.

Cheers

**Comment by justpeeet** [comment]
Have you installed gcc and make before running the `./scripts/build_pdo_snowflake.sh` command? No output seems like its not even trying because you are missing default libraries

**Comment by mrevjd** [comment]
> Have you installed gcc and make before running the `./scripts/build_pdo_snowflake.sh` command? No output seems like its not even trying because you are missing default libraries 

Thanks for your reply. But if you read my full comment you will notice I can run the script commands manually and even load the module.

**Comment by styxiak** [comment]
I installed today on ubuntu 22.10, php 8.1 without problems.
SSL Error was occuring when I have wrong account in dsn. When I specify correct account everything worked.

**Comment by mrevjd** [comment]
> I installed today on ubuntu 22.10, php 8.1 without problems. SSL Error was occuring when I have wrong account in dsn. When I specify correct account everything worked.

Just tried again in Ubuntu 22.04 and still now luck.
This is a WSL install

**Comment by mrevjd** [comment]
Managed to compile the module on Ubuntu 22.04 in WSL by manually going through the steps. Excluded the gcc command as phpize and make does that anyway.
