### ISSUE TITLE
Can't Load Extension due to Symbol Not Found in Flat Namespace

### ISSUE THREAD

**Issue by chrisguitarguy** [snowflakedb/pdo_snowflake#308]
> PHP Startup: Unable to load dynamic library 'pdo_snowflake' (tried: /opt/homebrew/lib/php/pecl/20220829/pdo_snowflake (dlopen(/opt/homebrew/lib/php/pecl/20220829/pdo_snowflake, 0x0009): tried: '/opt/homebrew/lib/php/pecl/20220829/pdo_snowflake' (no such file), '/usr/local/lib/pdo_snowflake' (no such file), '/usr/lib/pdo_snowflake' (no such file)), /opt/homebrew/lib/php/pecl/20220829/pdo_snowflake.so (dlopen(/opt/homebrew/lib/php/pecl/20220829/pdo_snowflake.so, 0x0009): symbol not found in flat namespace '_SF_BOOLEAN_FALSE')) in Unknown on line 0

In particular this bit:

> (dlopen(/opt/homebrew/lib/php/pecl/20220829/pdo_snowflake.so, 0x0009): symbol not found in flat namespace '_SF_BOOLEAN_FALSE'))

This same error happens on PHP 8.1 and 8.2 on an M1 Mac, the driver seems to install and work fine on Linux, however.

Any guidance here would be appreciated.

**Comment by sfc-gh-spanaite** [comment]
Hi @chrisguitarguy the driver is not yet supported on Mac M1. It is in plan, but I have no estimation yet.

**Comment by sfc-gh-dszmolka** [comment]
September's release 2.0.0 supports Mac ARM now.
See release notes at https://docs.snowflake.com/en/release-notes/clients-drivers/php-pdo-2023#version-2-0-0-september-29-2023

marking this one as closed.
