### ISSUE TITLE
SNOW-767048: No error if cmake is not present

### ISSUE THREAD

**Issue by max-novikov** [snowflakedb/pdo_snowflake#312]
If `cmake` is not present on the build system, the build script exits without any output.
While this issue is extremely stupid and rare, it still might be problematic for some, khm, users out there.
I would humbly suggest to add some kind of "Build failed" message.

**Comment by sfc-gh-spanaite** [comment]
Hi @max-novikov I've submitted an internal improvement to have an error message returned when `cmake` is not present. I consider this more of an improvement since `cmake` is listed as a Prerequisite on the Readme page.

**Comment by sfc-gh-spanaite** [comment]
Hi @max-novikov we're going to update the build script to fail with a proper error message. It will go most probably in the release of next month. With this in mind, I'll close this issue.
