### ISSUE TITLE
SNOW-919208: Can't build in docker container running on an M1 mac

### ISSUE THREAD

**Issue by SeanJA** [snowflakedb/pdo_snowflake#338]
1. What version of PDO/PHP driver are you using?

none yet, it won't build
   
2. What operating system and processor architecture are you using?

Linux docker container running on an M1 mac 
   
3. What version of C/C++ compiler are you using? 

```
$ gcc --version
gcc (Debian 10.2.1-6) 10.2.1 20210110

$ cmake --version
cmake version 3.18.4

$ clang --version
Debian clang version 11.0.1-2
Target: aarch64-unknown-linux-gnu
Thread model: posix

$ phpize --version
Configuring for:
PHP Api Version:         20220829
Zend Module Api No:      20220829
Zend Extension Api No:   420220829
```
5. What did you do?

followed the install instructions, got an error saying the file was in the wrong format:

> 49.12 /usr/bin/ld: libsnowflakeclient/lib/linux/libsnowflakeclient.a: error adding symbols: file in wrong format
> 49.12 collect2: error: ld returned 1 exit status
> 49.12 make: *** [Makefile:232: pdo_snowflake.la] Error 1

6. What did you expect to see?

   I guess it would install successfully?

**Comment by sfc-gh-igarish** [comment]
This is because PHP doesn't support AMD at that time. Could you please try again?

**Comment by EttoreCirillo** [comment]
i'm having the same problem with the same configuration on my MAC M1 : 

is this issue solved ? if so what should i do ?

**Comment by SeanJA** [comment]
> This is because PHP doesn't support ARM CPU at that time. Could you please try again?

I don't follow? Are you saying in September of 2023 php did not work on ARM CPUs?

**Comment by alexanderwburch** [comment]
Also having this problem... had a production workload building the PDO driver on php:8.1-cli running for years. Since i got my m1 laptop I can no longer build it with the same dockerfile
