### ISSUE TITLE
What is the difference between snowflake_close and snowflake_term?

### ISSUE THREAD

**Issue by smtakeda** [snowflakedb/pdo_snowflake#36]
snowflake_close is to close a session.
snowflake_term is to wipe out the SNOWFLAKE context.

I don't think we need to separate those two function calls but one should be good enough.

**Comment by notkriswagner** [comment]
I agree. Should we get rid of snowflake_close and just use snowflake_term?

**Comment by smtakeda** [comment]
yes, let's do it.

**Comment by smtakeda** [comment]
Maybe we should change name from snowflake_stmt_close to snowflake_stmt_term for consistency...
