### ISSUE TITLE
PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_snowflake' (tried: C:\xampp\php\ext\pdo_snowflake (The specified module could not be found), C:\xampp\php\ext\php_pdo_snowflake.dll (The specified module could not be found)) in Unknown on line 0

### ISSUE THREAD

**Issue by vishnuchoudhary2822** [snowflakedb/pdo_snowflake#370]
C:\Users\Administrator>php -v
PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_snowflake' (tried: C:\xampp\php\ext\pdo_snowflake (The specified module could not be found), C:\xampp\php\ext\php_pdo_snowflake.dll (The specified module could not be found)) in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'pdo_snowflake' (tried: C:\xampp\php\ext\pdo_snowflake (The specified module could not be found), C:\xampp\php\ext\php_pdo_snowflake.dll (The specified module could not be found)) in Unknown on line 0
PHP 8.2.12 (cli) (built: Oct 24 2023 21:15:15) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.2.12, Copyright (c) Zend Technologies

![Screenshot 2024-02-26 134333](https://github.com/snowflakedb/pdo_snowflake/assets/60024485/b2a55b1b-5919-4674-b571-7e0b6744b85f)

git clone https://github.com/snowflakedb/pdo_snowflake.git
cd pdo_snowflake

.\scripts\setup_php_sdk.bat x64 Release VS16 C:\xampp\php-sdk

.\scripts\run_setup_php.bat x64 Release VS16 16.11.34 C:\xampp\php-sdk

.\scripts\run_build_pdo_snowflake.bat x64 Release VS16 16.11.34 C:\xampp\php-sdk

extension=pdo_snowflake

C:\xampp\php\php.exe -dextension=ext\php_pdo_snowflake.dll -m

Hello 
I tried to configure Snowflake in Windows server but it's showing error
I need your assistance to configure it

Thanks

**Comment by vishnuchoudhary2822** [comment]
It's permission issue is resolved this issue Thanks

**Comment by vishnuchoudhary2822** [comment]
It's permission issue is resolved this issue Thanks

**Comment by sfc-gh-dszmolka** [comment]
glad to hear it's resolved for you; thank you for following up and closing the issue !
