### ISSUE TITLE
SNOW-1367604: Add PHP 8.3 Support

### ISSUE THREAD

**Issue by aldobarr** [snowflakedb/pdo_snowflake#382]
## What is the current behavior?
PHP 8.3 is not supported

## What is the desired behavior?
PHP 8.3 is supported

## How would this improve `pdo_snowflake`?
PHP 8.3 is already starting to be upgraded to by many production environments. However any system relying on snowflake is unable to do so.

## References, Other Background
N/A

## What is your Snowflake account identifier, if any?
 N/A

**Comment by salvor-hardin** [comment]
I have php 8.3.6 and this driver has worked fine every version of 8.3.x

**Comment by aldobarr** [comment]
> I have php 8.3.6 and this driver has worked fine every version of 8.3.x

Hm, it did not compile for me

**Comment by sfc-gh-dszmolka** [comment]
(relevant PR is https://github.com/snowflakedb/pdo_snowflake/pull/383, already merged, waiting for release)

**Comment by sfc-gh-dszmolka** [comment]
PHP 8.3 support released with v3.0.0 (and PHP 8.0 deprecated)
