### ISSUE TITLE
SNOW-1452220: VS2019 no longer available - Could not determine 'vs16' directory

### ISSUE THREAD

**Issue by MaxenceSAUNIER** [snowflakedb/pdo_snowflake#386]
1. What version of PDO/PHP driver are you using?
8.2.18
   
2. What operating system and processor architecture are you using?
x64 Windows 11
   
3. What version of C/C++ compiler are you using?
Microsoft Visual C++ 2015-2019 Redistribuable (x64) - 14.29.30153
   
4. What did you do?

I have follow « Building the Driver on Windows » steps.
At the step « 4.  Download and build the PHP source code. » I have this error:
```
>> .\scripts\run_setup_php.bat x64 Release VS16 8.2.18 .\php-sdk
=== setting up global environment variables
"Building with platform: x64, build type: Release, visual studio version: VS16, cmake generator: Visual Studio 16 2019"
Could not determine 'vs16' directory
```

Visual Studio 2019 (VS16) is no longer available for download
https://my.visualstudio.com/Downloads?q=visual%20studio%202019&wt.mc_id=o~msft~vscom~older-downloads

5. What did you expect to see?

6. Can you set logging to DEBUG and collect the logs?

   
7. What is your Snowflake account identifier, if any? (Optional)

**Comment by sfc-gh-dszmolka** [comment]
hi and thank you for reporting this; will take a look

**Comment by sfc-gh-dszmolka** [comment]
can you please check if downloading Visual Studio 2019 from https://learn.microsoft.com/en-us/visualstudio/releases/2019/redistribution#vs2019-download helps moving forward ?

**Comment by MaxenceSAUNIER** [comment]
It seems to download the correct version, I'll let you know as soon as I test.

**Comment by MaxenceSAUNIER** [comment]
It works like a charm, thanks you very much.
