### ISSUE TITLE
SNOW-1633600: Add Binded Variable Support

### ISSUE THREAD

**Issue by aldobarr** [snowflakedb/pdo_snowflake#396]
## What is the current behavior?
Using standard bind variables with the PDO driver returns an error that the variable is not set. I.e.
`Bind variable :date_start not set. (Connection: snowflake...`

## What is the desired behavior?
As with any PDO driver, data should be binded and properly handled to the respective variables based on an array such as
`query ... WHERE date BETWEEN :date_start AND :date_end`
`$bindings = ['date_start' => 'Y-m-d', 'date_end' => 'Y-m-d'];`

## How would this improve `pdo_snowflake`?
This is functionality that would be expected of any PDO driver. It's also quite jarring that the PHP driver is the only one that doesn't support this? I was not expecting this at all and could not understand why I was receiving the error mentioned above. It's also not mentioned anywhere in this repository's readme so it's hard to even know that it's just not supported until you dig through the general snowflake documentation and find this tiny almost throwaway note:

![image](https://github.com/user-attachments/assets/47e38eb7-1d06-4d26-b943-b14375b69d14)

I think most people using PDO would expected binded variables like the above example to be a basic core feature as that's the most convenient and safest way to query data with user input especially for complex queries where keeping track of placeholder (`?`) orderings becomes messy.

## References, Other Background
N/A

## What is your Snowflake account identifier, if any?
 N/A

**Comment by sfc-gh-dszmolka** [comment]
hi and thank you for raising this enhancement request. the team will consider for future plans. cannot give any timeline for implementation, but if this capability is especially important for you, please do reach out to your Snowflake account team and let them know. 

couple things i would also add.
1. unfortunately, binding timestamps is really not supported at the moment: https://github.com/snowflakedb/libsnowflakeclient/blob/v1.0.12/lib/results.c#L238
some other datatypes are also missing from the underlying C API, on which the PHP driver is based. So implementation will also be done in the underlying API probably, and not this library.
2. for some datatype, binding _is_ supported: https://github.com/snowflakedb/pdo_snowflake/blob/v3.0.1/tests/bind_named_parameters.phpt
3. there are plans to address 1. , without any committed timeline available to me at this moment, but it's on the dev team radar. 

Hope this information helps somewhat.

**Comment by aldobarr** [comment]
> hi and thank you for raising this enhancement request. the team will consider for future plans. cannot give any timeline for implementation, but if this capability is especially important for you, please do reach out to your Snowflake account team and let them know.
> 
> couple things i would also add.
> 
> 1. unfortunately, binding timestamps is really not supported at the moment: https://github.com/snowflakedb/libsnowflakeclient/blob/v1.0.12/lib/results.c#L238
>    some other datatypes are also missing from the underlying C API, on which the PHP driver is based. So implementation will also be done in the underlying API probably, and not this library.
> 2. for some datatype, binding _is_ supported: https://github.com/snowflakedb/pdo_snowflake/blob/v3.0.1/tests/bind_named_parameters.phpt
> 3. there are plans to address 1. , without any committed timeline available to me at this moment, but it's on the dev team radar.
> 
> Hope this information helps somewhat.

In my specific example I'm using a `Y-m-d` formatted string (or sometimes `Y-m-d H:i:s` but a string in either case) so I would have expected it to just be binded as a string 🤔

**Comment by sfc-gh-dszmolka** [comment]
i missed that part it's a string in this case. Then in this case, it is unrelated to the points 1 and 3 above. Testing the string bindings with
```php
    $sth = $dbh->prepare("insert into t(c1, c2) values(:v1,:v2)");
    $bindings = ['v1' => 11, 'v2' => 'Hello'];
    $sth->execute($bindings);
```

just worked, so something else might be wrong here.

Do you think you could provide a full PHP script which I could look at and try to run, which script reproduces the issue for you ? Thank you in advance!

**Comment by aldobarr** [comment]
> i missed that part it's a string in this case. Then in this case, it is unrelated to the points 1 and 3 above. Testing the string bindings with
> 
> ```
>     $sth = $dbh->prepare("insert into t(c1, c2) values(:v1,:v2)");
>     $bindings = ['v1' => 11, 'v2' => 'Hello'];
>     $sth->execute($bindings);
> ```
> 
> just worked, so something else might be wrong here.
> 
> Do you think you could provide a full PHP script which I could look at and try to run, which script reproduces the issue for you ? Thank you in advance!

I'm not sure I can provide you with the exact script we're using, but I can tell you we're using:

1. php 8.2
2. Laravel 11
3. The `yoramdelangen/laravel-pdo-odbc` package (v1.2.5) for providing a Laravel driver for snowflake pdo (using snowflake_native to ensure the driver uses PDO instead of ODBC)

And the query looks something along these lines:
```php
        $table = config('database.snowflake_stats');
        $sql = <<<SQL
            -- stats $logType $logRollup
            WITH stats AS (
                SELECT
                    # all of the fields we're selecting
                FROM $table stats
                WHERE
                    DATE BETWEEN :date_start AND :date_end
                    AND USER_ID = :user_id
                GROUP BY 1,2,3
            )
            SELECT
                stats.*
            FROM stats
            LIMIT 1
        SQL;

        $bindings = [
            'date_start' => '2024-06-19',
            'date_end'   => '2024-06-20',
            'user_id'    => 1
        ];

        return new Collection(DB::connection(config('database.snowflake'))->select($sql, $bindings));
```
And the error:
```
{"class":"Illuminate\\Database\\QueryException","message":"SQLSTATE[42601]: Syntax error: 2049 SQL compilation error: error line 81 at position 25
Bind variable :date_start not set. (Connection: snowflake...
```

I was able to reproduce this locally and confirm that despite the variables definitely having been set to the statement, the exception was thrown.

**Comment by sfc-gh-dszmolka** [comment]
Thank you for the above info! So this is what I tried:
1. setup tables etc
```sql
-- Snowsight GUI - create table and populate it
create database test_db;
create schema php;
create or replace table issue396 (
    date date,
    user_id number(10,0)
);
insert into issue396 values (to_date('2024-06-19'), 1);
insert into issue396 values (to_date('2024-06-11'), 2);
select * from issue396;
/*
DATE	USER_ID
2024-06-19	1
2024-06-11	2
*/
```

2. now try to query those tables with binding. I'm using the native `pdo_snowflake` driver , version 3.0.0 without any framework. Just built it and using it from CLI as the following, using your snippet:
```php
# cat issue396.php 
<?php
  $account = getenv('SFACCOUNT');
  $user = getenv('SFUSER');
  $password = getenv('SFPASS'); 
 
  $dbh = new PDO("snowflake:account=$account", $user, $password);
  $dbh->setAttribute( PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION );
  echo "Connected\n";
 
  $sql = <<<SQL
            -- stats $logType $logRollup
            WITH stats AS (
                SELECT
                  1,2
                FROM test_db.php.issue396 stats
                WHERE
                    DATE BETWEEN :date_start AND :date_end
                    AND USER_ID = :user_id
                GROUP BY 1,2
            )
            SELECT
                stats.*
            FROM stats
            LIMIT 1
        SQL;

  $bindings = [
            'date_start' => '2024-06-19',
            'date_end'   => '2024-06-20',
            'user_id'    => 1
            ];

  $sth = $dbh->prepare($sql);
  $sth->execute($bindings);
  while ($row=$sth->fetch(PDO::FETCH_NUM)) {
      echo "RESULT: " . $row[0] . " " . $row[1] . "\n";
  }
  $dbh = null;
  echo "OK\n";
?>
```
3. result:
```
# php -f issue396.php 
Connected
PHP Warning:  Undefined variable $logType in /test/issue396.php on line 11
PHP Warning:  Undefined variable $logRollup in /test/issue396.php on line 11
RESULT: 1 2
OK
```

looks to be able to correctly query Snowflake with the named variable bindings, using the same name(s).

From what I already see, one difference could be that I'm preparing the statement before adding the bindings to it; while `connection(..)->select(..)`, even without knowing the third party library, to me suggests that no prepare is done before executing the statement which might also explain why Snowflake engine complains about the missing bind variables.

Can you please try the same, without the aforementioned framework, only using the Snowflake driver ?  Does it work for you ?

Also perhaps looking around in the third party library could provide useful examples how to use it with named bind variables; I checked it superficially and it seems to have `prepare` and `bindValues`. 

For now, this doesn't seem to be a limitation on the `pdo_snowflake` side (except of course the ones called out in the first comment), but if you find a bug pointing to this library, please share more details about it. 

(if needed you can enable TRACE level logs by adding
```ini
pdo_snowflake.logdir=/tmp
pdo_snowflake.loglevel=DEBUG
```
to the snowflake ini file)

**Comment by aldobarr** [comment]
> 3\. yoramdelangen

Yeah come to think of it our prod environment is not broken and it should be on the previous version of the Laravel package (1.2.4) so the issue might actually be on the package's side. I'll create a report there.

**Comment by sfc-gh-dszmolka** [comment]
Thank you. I'm going to close this for now but please feel free to comment and i can reopen if further investigation is necessary with the Snowflake PHP driver.
