### ISSUE TITLE
Allow to set the statement parameters before query

### ISSUE THREAD

**Issue by smtakeda** [snowflakedb/pdo_snowflake#40]
Due to the fix for #35, all parameters are cleared in query/prepare.
This prevents from setting the statement attribute *before* query.

**Comment by smtakeda** [comment]
So far no stmt attribute is supported. async will be in the future version.

Implementation note: since there isn't many parameters, we agreed to have individual parameters in SNOWFLAKE_STMT instead of a hash including all values.

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
