### ISSUE TITLE
SNOW-1729304: SQLSTATE[08001] [240012] curl_easy_perform() failed. err: Problem with the SSL CA cert (path? access rights?), CA Cert file: Not Specified

### ISSUE THREAD

**Issue by alexTitakoff** [snowflakedb/pdo_snowflake#400]
Good afternoon!

1.Php versions 8.3
pdo - the latest version that comes from the  repository.
2. OS: Docker container Linux.

A \certificate error occurs during the test connection. 
The Docker container on localhost is used. To disable OCSP, use the insecure_mode  parameter. 

Example of debugging code.

`try {
    $dbh = new \PDO("snowflake:account=XXXXXXX;warehouse=XXXXX;database=XXXXX;schema=XXXX;insecure_mode=true;", 'XXXXX', 'XXXXXX');
} catch (PDOException $e) {   
    trace_log($e->getMessage());
    die($e->getMessage());
}

$sql = "SELECT * FROM DLD_LAND_REGISTRY LIMIT 10";
$sth = $dbh->query($sql);

while ($row = $sth->fetch(\PDO::FETCH_NUM)) {
    echo $row;
    return;
}`

The parameter is marked with. But the error still occurs  

SQLSTATE[08001] [240012] curl_easy_perform() failed. err: Problem with the SSL CA cert (path? access rights?), CA Cert file: Not Specified

What could be the error? Thank you!

**Comment by sfc-gh-dszmolka** [comment]
hi ! can you please
* make sure `account=XXXX` has the proper accountname, as either `myorg-myaccount` (regionless version) or the regioned version as mentioned in [Account Identifiers](https://docs.snowflake.com/en/user-guide/admin-account-identifier#format-2-account-locator-in-a-region). E.g. in AWS EU Frankfurt it's `xy12345.eu-central-1`, and not just `xy12345` (it would go to AWS US West)

If you're unsure what your account identifier is, you can login to Snowsight GUI , after login look at the URL (`https://app.snowflake.com/myorg/myaccount`) and copy `myorg/myaccount` as `myorg-myaccount` (replacing the `/` with `-`)

* if it still doesn't work, please set DEBUG level logs by configuring
```ini
pdo_snowflake.logdir=/tmp
pdo_snowflake.loglevel=TRACE"

```
in your .ini, reproduce th issue, collect logs from `logdir` and sharing them here. Don't forget to edit out the sensitive information. 

Also make sure that `pdo_snowflake.cacert` points to the `cacert.pem` which came with the drier. E.g. `/etc/php/8.2/cli/conf.d/cacert.pem`

**Comment by alexTitakoff** [comment]
Thank you for the prompt response!

I apologize, I got a bit lost in the settings and guides for adapting to Docker. I missed the step for configuring cacert.pem.

"In the same directory that contains the PHP configuration files, create a config file named 20-pdo_snowflake.ini that contains the following settings (or in case using Configuration File (php.ini) Path:, add the following lines to php.ini):
```extension=pdo_snowflake.so
pdo_snowflake.cacert=<path to PHP config directory>/cacert.pem
# pdo_snowflake.logdir=/tmp     # location of log directory
# pdo_snowflake.loglevel=DEBUG  # log level```

Everything is working now, thank you for pointing out that important detail!

**Comment by sfc-gh-dszmolka** [comment]
good to hear your problem is resolved ;) thanks for the feedback!
