### ISSUE TITLE
Implement Ctrl+C to stop a query support

### ISSUE THREAD

**Issue by smtakeda** [snowflakedb/pdo_snowflake#6]
Goal
- Provide a signal hander for the applications to stop a query.
- Provide an example of Ctrl+C to stop a query.

TBD:
- Do we want to support Ctrl+C behavior by default.

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
