### ISSUE TITLE
Support named binding

### ISSUE THREAD

**Issue by smtakeda** [snowflakedb/pdo_snowflake#68]
Looks like we may be able to support named binding.

**Comment by notkriswagner** [comment]
From @zoltan-fedor

> Hi,
> I have seen in the README (https://github.com/snowflakedb/pdo_snowflake#limitations) and also in #159 that the named placeholders are currently not supported.
> 
> Could this be added please?
> 
> We are doing a migration to Snowflake with lots of legacy code which we would need to majorly rewrite to switch from named placeholders to positional ones.
> 
> Thanks

**Comment by smtakeda** [comment]
Filing a JIRA.

**Comment by zoltan-fedor** [comment]
Thanks @smtakeda, we are very much looking forward to use the named placeholders, as our migration would be in deep trouble if it would need to rewrite all our existing code migrating away from Oracle to take the named placeholders out from it to replace with positional ones.

**Comment by h-chaturvedi** [comment]
This has been fixed and committed as part of #204 . Closing this now.

**Comment by h-chaturvedi** [comment]
This has been fixed as part of commit #204 . Closing this issue now.

**Comment by zoltan-fedor** [comment]
Thanks this is great!

**Comment by zoltan-fedor** [comment]
Unfortunately trying to load the library following this commit we see `undefined symbol: pdo_sf_param_store_get`. See more at https://github.com/snowflakedb/pdo_snowflake/issues/208

**Comment by zoltan-fedor** [comment]
@h-chaturvedi, please ignore.
This (https://github.com/snowflakedb/pdo_snowflake/issues/208) happened because I have applied this fix (https://github.com/snowflakedb/pdo_snowflake/issues/198) without rewriting it to include the new `snowflake_paramstore.o` file.
