### ISSUE TITLE
Support Ctrl+C well

### ISSUE THREAD

**Issue by smtakeda** [snowflakedb/pdo_snowflake#71]
By default, PHP CLI allows the uses to interrupt a script by Ctrl+C. A problem is it leaks lot of memory. Is there any way to gracefully free all memory?

Note this could be PHP fundamental issue. Need further investigation.

**Comment by jianshenghuang** [comment]
Curious on why Ctrl+C leaks a lot of memory.

**Comment by smtakeda** [comment]
In PHP CLI, SIGINT skips freeing allocated memory and exits. valgrind shows lots of memory leaks. For CLI, it should be fine as the process exits anyway, but it won't close a session, so the session is leaked anyway.

**Comment by smtakeda** [comment]
Duplicate #6
