### ISSUE TITLE
Build PDO for Windows

### ISSUE THREAD

**Issue by smtakeda** [snowflakedb/pdo_snowflake#99]
- Build Curl and Openssl for Windows
- Commit library and headers
- Build PDO for Windows
- Pass all existing tests

**Comment by tomasfejfar** [comment]
You might be insterested in https://www.appveyor.com/ for Windows CI build.

**Comment by smtakeda** [comment]
Thanks for suggestion. We already incorporate Appveyor for https://github.com/snowflakedb/libsnowflakeclient, so we how to use it.

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
